import type { Locale } from '../../i18n'

export const creatorMessages = {
  "pt-BR": {
    "creator_label_game": "Jogo",
    "creator_label_runtime": "Runtime",
    "creator_enhancements": "Melhorias",
    "creator_dependencies": "Dependências",
    "creator_launch_and_environment": "Execução e Ambiente",
    "creator_label_scripts": "Scripts",
    "creator_review_and_generate": "Revisão e Gerar",
    "creator_runtime_default_do_not_override": "Padrão do runtime (não alterar)",
    "creator_desktop": "Desktop",
    "creator_documents": "Documentos",
    "creator_downloads": "Downloads",
    "creator_music": "Músicas",
    "creator_pictures": "Imagens",
    "creator_videos": "Vídeos",
    "creator_auto_detect": "Auto detectar",
    "creator_local_hard_disk": "Disco rígido local",
    "creator_network_share": "Compartilhamento de rede",
    "creator_floppy_disk": "Disquete",
    "creator_cd_rom": "CD-ROM",
    "creator_proton_version": "Versão do Proton",
    "creator_wine_version": "Versão do Wine",
    "creator_preferred_runtime_version": "Versão de runtime (preferida)",
    "creator_target_proton_version_used_by_the_orchestrator_when_pref": "Versão alvo do Proton usada pelo orquestrador quando a preferência está em Proton.",
    "creator_expected_wine_version_identifier_when_preference_is_wine": "Versão/identificador de Wine esperada quando a preferência está em Wine.",
    "creator_preferred_runtime_version_when_auto_mode_picks_proton_wi": "Versão preferida para runtime quando o modo Auto escolher Proton/Wine conforme disponibilidade.",
    "creator_importing_reg_requires_an_absolute_path_in_browser_lan_m": "Importação de .reg requer caminho absoluto. No modo navegador (LAN), selecione no app Tauri local.",
    "creator_mounted_folder_browser_requires_an_absolute_game_root_pa": "Navegador de pastas montadas requer caminho absoluto da pasta do jogo. Use o app Tauri local.",
    "creator_select_an_executable_first_to_define_the_game_folder": "Selecione um executável primeiro para definir a pasta do jogo.",
    "creator_in_browser_lan_mode_the_mini_folder_browser_cannot_acces": "No modo navegador (LAN), o mini navegador de pastas não consegue acessar o filesystem. Use o app Tauri local.",
    "creator_language": "Idioma",
    "creator_dark": "Escuro",
    "creator_light": "Claro",
    "creator_system": "Sistema",
    "creator_theme": "Tema",
    "creator_label_enabled": "Ativado",
    "creator_label_disabled": "Desativado",
    "creator_label_mandatory": "Obrigatório",
    "creator_use_wine_default": "Padrão do Wine",
    "creator_label_actions": "Ações",
    "creator_label_action": "Ação",
    "creator_label_add": "Adicionar",
    "creator_add_item": "Adicionar item",
    "creator_enter_a_value_and_confirm_to_add_it_to_the_list": "Informe um valor e confirme para adicioná-lo à lista.",
    "creator_fill_in_key_and_value_to_add_a_new_row": "Preencha chave e valor para adicionar uma nova linha.",
    "creator_choose_file": "Escolher arquivo",
    "creator_select_a_file_to_fill_this_field_automatically": "Selecione um arquivo para preencher este campo automaticamente.",
    "creator_label_cancel": "Cancelar",
    "creator_label_confirm": "Confirmar",
    "creator_label_remove": "Remover",
    "creator_no_item_added": "Nenhum item adicionado.",
    "creator_key": "Chave",
    "creator_value": "Valor",
    "creator_open_menu": "Abrir menu",
    "creator_step": "Etapa",
    "creator_game_name": "Nome do jogo",
    "creator_name_shown_in_splash_and_local_database": "Nome mostrado na splash e no banco local.",
    "creator_main_executable_exe": "Executável principal (.exe)",
    "creator_use_picker_to_select_the_real_game_executable": "Use o picker para selecionar o .exe real do jogo.",
    "creator_select_file": "Selecionar arquivo",
    "creator_game_root_folder": "Pasta raiz do jogo",
    "creator_defaults_to_the_main_executable_folder_but_can_be_change": "Por padrão usa a pasta do executável principal, mas pode ser alterada se o .exe estiver em subpasta.",
    "creator_choose_another": "Escolher outra",
    "creator_choose_game_root_folder": "Escolher pasta raiz do jogo",
    "creator_the_game_root_must_be_an_ancestor_of_the_folder_that_con": "A pasta raiz deve ser um ancestral da pasta onde está o executável principal.",
    "creator_this_guided_flow_requires_an_absolute_executable_path_lo": "Esse fluxo guiado precisa de um caminho absoluto do executável (modo Tauri local).",
    "creator_use_system_picker": "Usar seletor do sistema",
    "creator_executable_folder_breadcrumb": "Breadcrumb da pasta do executável",
    "creator_executable_path": "Caminho do executável",
    "creator_select_which_ancestor_level_should_be_the_game_root": "Selecione qual nível acima deve ser a pasta raiz do jogo.",
    "creator_same_directory_as_executable_automatic": "Mesmo diretório do executável (automático)",
    "creator_close": "Fechar",
    "creator_sha_256_hash": "Hash SHA-256",
    "creator_main_identifier_for_profile_and_per_game_prefix": "Identificador principal para perfil e prefixo por jogo.",
    "creator_final_prefix_path": "Prefix path final",
    "creator_automatically_calculated_from_executable_hash": "Calculado automaticamente a partir do hash do executável.",
    "creator_prefix_path_copied": "Path do prefixo copiado.",
    "creator_failed_to_copy_to_clipboard": "Falha ao copiar para área de transferência.",
    "creator_copy": "Copiar",
    "creator_extracted_icon": "Ícone extraído",
    "creator_game_icon_preview_for_easier_visual_identification": "Preview do ícone do jogo para facilitar identificação visual.",
    "creator_visual_is_ready_real_extraction_will_be_wired_to_backend": "Visual pronto. A extração real será conectada ao backend na próxima etapa.",
    "creator_no_extracted_icon": "Sem ícone extraído",
    "creator_extract_icon": "Extrair ícone",
    "creator_launch_arguments": "Argumentos de launch",
    "creator_extra_arguments_passed_to_game_executable": "Argumentos extras passados para o exe do jogo.",
    "creator_windowed": "-windowed",
    "creator_add_argument": "Adicionar argumento",
    "creator_no_launch_argument_added": "Nenhum argumento adicionado.",
    "creator_argument": "Argumento",
    "creator_required_files": "Arquivos obrigatórios",
    "creator_if_any_listed_file_is_missing_from_the_game_folder_start": "Se algum arquivo listado não existir na pasta do jogo, a inicialização é bloqueada.",
    "creator_data_core_dll": "./data/core.dll",
    "creator_add_file": "Adicionar arquivo",
    "creator_pick_file_from_game_folder": "Escolher arquivo na pasta do jogo",
    "creator_no_file_added": "Nenhum arquivo adicionado.",
    "creator_relative_file": "Arquivo relativo",
    "creator_mounted_folders": "Pastas montadas",
    "creator_maps_a_folder_inside_the_game_to_a_windows_target_inside": "Mapeia uma pasta dentro do jogo para um destino Windows dentro do prefixo (ex.: saves em Documentos).",
    "creator_no_mount_added": "Nenhuma montagem adicionada.",
    "creator_relative_source": "Origem relativa",
    "creator_windows_target": "Destino Windows",
    "creator_create_source": "Criar origem",
    "creator_yes": "Sim",
    "creator_no": "Não",
    "creator_folder": "Pasta",
    "creator_remove_mount": "Remover montagem",
    "creator_add_mount": "Adicionar montagem",
    "creator_set_relative_source_and_windows_target_to_create_the_mou": "Defina origem relativa e destino Windows para criar a montagem.",
    "creator_relative_source_e_g_save": "Origem relativa (ex.: save)",
    "creator_browse_folders": "Navegar pastas",
    "creator_windows_target_c_users": "Destino Windows (C:\\users\\...)",
    "creator_create_source_if_missing": "Criar origem se estiver ausente",
    "creator_select_folder_inside_game": "Selecionar pasta dentro do jogo",
    "creator_mini_browser_restricted_to_the_game_root_to_prevent_moun": "Mini navegador restrito à pasta raiz do jogo para evitar montagens fora do projeto.",
    "creator_current_path": "Caminho atual",
    "creator_folder_breadcrumb": "Breadcrumb de pastas",
    "creator_loading_folders": "Carregando pastas...",
    "creator_no_subfolder_found": "Nenhuma subpasta encontrada.",
    "creator_select_this_folder": "Selecionar esta pasta",
    "creator_use_this_folder": "Usar esta pasta",
    "creator_general_runtime_preference": "Preferência geral de runtime",
    "creator_macro_priority_among_auto_proton_and_wine": "Prioridade macro entre Auto, Proton e Wine.",
    "creator_required_version": "Versão obrigatória",
    "creator_when_enabled_requires_the_configured_runtime_version_to": "Quando ativado, exige exatamente a versão configurada para executar.",
    "creator_auto_update": "Auto update",
    "creator_updates_runtime_metadata_when_applicable_before_launchin": "Atualiza metadados do runtime quando aplicável antes da execução.",
    "creator_enables_synchronization_optimizations_in_runtime": "Ativa otimizações de sincronização no runtime.",
    "creator_enables_fsync_optimizations_when_supported": "Ativa otimizações FSYNC quando suportado.",
    "creator_controls_umu_run_usage_according_to_enforcement_policy": "Controla uso de umu-run conforme política de obrigatoriedade.",
    "creator_steam_runtime": "Steam Runtime",
    "creator_defines_whether_steam_runtime_is_mandatory_optional_or_b": "Define se steam runtime é obrigatório, opcional ou bloqueado.",
    "creator_policy_for_local_easy_anticheat_runtime": "Política para runtime local do Easy AntiCheat.",
    "creator_policy_for_local_battleeye_runtime": "Política para runtime local do BattleEye.",
    "creator_defines_gamescope_policy_and_syncs_with_requirements_gam": "Define política do gamescope e sincroniza com requirements.gamescope.",
    "creator_gamescope_is_disabled_enable_it_to_configure_resolution": "Gamescope está desativado. Ative para configurar resolução, upscale e janela.",
    "creator_upscale_method": "Método de upscale",
    "creator_method_used_by_gamescope_for_upscaling": "Método usado pelo gamescope para upscale.",
    "creator_window_type": "Tipo de janela",
    "creator_defines_gamescope_window_behavior": "Define comportamento da janela no gamescope.",
    "creator_game_resolution": "Resolução do jogo",
    "creator_game_render_resolution_width_x_height": "Resolução renderizada pelo jogo (largura x altura).",
    "creator_display_resolution": "Resolução da tela",
    "creator_final_gamescope_output_resolution_width_x_height": "Resolução final de saída do gamescope (largura x altura).",
    "creator_auto": "Auto",
    "creator_use_monitor_resolution": "Obter resolução do monitor",
    "creator_enable_fps_limiter": "Limitar FPS",
    "creator_enables_gamescope_fps_limiter": "Ativa limitador de FPS do gamescope.",
    "creator_force_grab_cursor": "Forçar captura de cursor",
    "creator_forces_relative_mouse_mode_to_avoid_focus_loss": "Força modo relativo de mouse para evitar perda de foco.",
    "creator_fps_limit": "FPS limite",
    "creator_fps_limit_when_game_is_focused": "Limite de FPS quando o jogo está em foco.",
    "creator_fps_limit_without_focus": "FPS sem foco",
    "creator_fps_limit_when_game_loses_focus": "Limite de FPS quando o jogo perde foco.",
    "creator_gamescope_additional_options": "Opções adicionais do gamescope",
    "creator_add_extra_flags_that_will_be_appended_to_the_gamescope_c": "Adicione flags extras que serão anexadas ao comando do gamescope.",
    "creator_prefer_vk_device_1002_73bf": "--prefer-vk-device 1002:73bf",
    "creator_add_option": "Adicionar opção",
    "creator_defines_gamemode_policy": "Define política do gamemode.",
    "creator_defines_mangohud_policy": "Define política do MangoHud.",
    "creator_policy_for_enabling_wine_wayland": "Política para ativar Wine-Wayland.",
    "creator_policy_for_hdr_depends_on_wine_wayland": "Política para HDR (depende de Wine-Wayland).",
    "creator_controls_automatic_dxvk_nvapi_setup": "Controla aplicação automática de DXVK-NVAPI.",
    "creator_controls_mandatory_usage_of_wine_staging_runtime": "Controla obrigatoriedade de runtime Wine com staging.",
    "creator_use_dedicated_gpu": "Usar GPU dedicada",
    "creator_exports_prime_render_offload_variables_to_try_using_the": "Exporta variáveis de PRIME render offload para tentar usar a GPU dedicada em sistemas híbridos.",
    "creator_enabled_automatically_when_at_least_one_verb_is_configur": "Ativa automaticamente quando existir ao menos um verbo configurado. Use a busca para adicionar verbos do catálogo.",
    "creator_remove_verb": "Remover verbo",
    "creator_failed_to_load_winetricks_catalog": "Erro ao carregar o catálogo winetricks",
    "creator_search_and_add_verbs_e_g_vcrun_corefonts": "Buscar e adicionar verbos (ex.: vcrun, corefonts)",
    "creator_the_local_remote_catalog_could_not_be_loaded_you_can_sti": "O catálogo local/remoto não pôde ser carregado. Você ainda pode atualizar o catálogo manualmente.",
    "creator_type_at_least_2_characters_to_search_verbs_in_the_catalo": "Digite ao menos 2 caracteres para buscar verbos no catálogo.",
    "creator_no_items_found": "Nenhum item encontrado.",
    "creator_loading_catalog_in_background": "Carregando catálogo em segundo plano...",
    "creator_loading": "Carregando...",
    "creator_refresh_catalog": "Atualizar catálogo",
    "creator_source": "Fonte:",
    "creator_catalog": "Catálogo:",
    "creator_registry_keys": "Chaves de registro",
    "creator_table_of_keys_applied_to_prefix_after_bootstrap": "Tabela de chaves aplicadas no prefixo após bootstrap.",
    "creator_no_key_added": "Nenhuma chave adicionada.",
    "creator_path": "Path",
    "creator_name": "Nome",
    "creator_type": "Tipo",
    "creator_remove_key": "Remover chave",
    "creator_add_key": "Adicionar chave",
    "creator_add_registry_key": "Adicionar chave de registro",
    "creator_fill_fields_and_confirm_to_add_row": "Preencha os campos e confirme para adicionar a linha.",
    "creator_path_hkcu": "Path (HKCU\\...)",
    "creator_key_name": "Nome da chave",
    "creator_type_reg_sz": "Tipo (REG_SZ)",
    "creator_add_from_file_reg": "Adicionar de arquivo (.reg)",
    "creator_reg_import_warnings": "Avisos da importação de .reg",
    "creator_some_lines_were_ignored_or_imported_with_fallback_review": "Algumas linhas foram ignoradas ou importadas com fallback. Revise os avisos abaixo.",
    "creator_extra_system_dependencies": "Dependências extras do sistema",
    "creator_additional_dependencies_validated_in_doctor_by_command_e": "Dependências adicionais verificadas no doctor por comando/env/path.",
    "creator_command": "Comando",
    "creator_env_vars": "Variáveis",
    "creator_default_paths": "Paths padrão",
    "creator_unnamed": "Sem nome",
    "creator_remove_dependency": "Remover dependência",
    "creator_no_extra_dependency_added": "Nenhuma dependência extra adicionada.",
    "creator_add_dependency": "Adicionar dependência",
    "creator_add_extra_system_dependency": "Adicionar dependência extra do sistema",
    "creator_define_how_doctor_can_detect_this_dependency_command_env": "Informe como o doctor pode detectar essa dependência (comando, variáveis e paths padrão).",
    "creator_dependency_name": "Nome da dependência",
    "creator_terminal_command_e_g_mangohud": "Comando no terminal (ex.: mangohud)",
    "creator_environment_vars_comma_separated": "Variáveis de ambiente (separadas por vírgula)",
    "creator_default_paths_comma_separated": "Paths padrão (separados por vírgula)",
    "creator_winecfg_overrides_do_not_replace_everything": "Overrides do winecfg (não substituem tudo)",
    "creator_settings_in_this_tab_are_additive_overrides_on_top_of_wi": "As configurações desta aba são adicionais ao padrão do prefixo/Wine. Se você deixar em \"Padrão do Wine\", o orquestrador não força esse item.",
    "creator_dll_overrides": "Substituição de DLL",
    "creator_configures_per_dll_overrides_such_as_native_builtin": "Configura overrides por DLL como native/builtin.",
    "creator_no_override_added": "Nenhum override adicionado.",
    "creator_dll": "DLL",
    "creator_mode": "Modo",
    "creator_add_dll_override": "Adicionar DLL override",
    "creator_set_the_dll_name_and_override_mode": "Defina o nome da DLL e o modo de substituição.",
    "creator_windows_version_winecfg": "Versão do Windows (winecfg)",
    "creator_optional_override_for_the_windows_version_reported_by_th": "Override opcional da versão do Windows reportada pelo prefixo. Se não configurar, mantém o padrão do runtime/prefixo.",
    "creator_graphics": "Gráficos",
    "creator_equivalent_to_the_graphics_tab_in_winecfg_everything_her": "Equivalente à aba Gráficos do winecfg. Tudo aqui é adicional ao padrão do prefixo.",
    "creator_graphics_incremental_overrides": "Gráficos = ajustes incrementais",
    "creator_these_items_do_not_recreate_the_prefix_they_only_add_win": "Esses itens não recriam o prefixo. Eles apenas adicionam overrides de comportamento do winecfg sobre o que já existe no prefixo atual.",
    "creator_automatically_capture_mouse_in_fullscreen_windows": "Capturar o mouse automaticamente em janelas em tela cheia",
    "creator_equivalent_to_winecfg_auto_capture_mouse_option": "Equivalente à opção de captura automática do winecfg.",
    "creator_allow_the_window_manager_to_decorate_windows": "Permitir que o gerenciador de janelas decore as janelas",
    "creator_controls_window_decorations_managed_by_the_wm": "Controla decorações de janela gerenciadas pelo WM.",
    "creator_allow_the_window_manager_to_control_windows": "Permitir que o gerenciador de janelas controle as janelas",
    "creator_lets_the_wm_control_window_position_focus_state": "Permite que o WM controle posição/foco/estado das janelas.",
    "creator_emulate_a_virtual_desktop": "Emular uma área de trabalho virtual",
    "creator_when_enabled_the_game_runs_inside_a_wine_virtual_desktop": "Quando ativo, o jogo roda dentro de um desktop virtual do Wine.",
    "creator_virtual_desktop_size": "Tamanho da área de trabalho virtual",
    "creator_set_width_x_height_e_g_1280_x_720": "Informe largura x altura (ex.: 1280 x 720).",
    "creator_screen_resolution_dpi": "Resolução da tela (DPI)",
    "creator_slider_from_96_dpi_to_480_dpi_if_unset_wine_default_is_u": "Slider de 96 ppp até 480 ppp. Se não configurar, usa o padrão do Wine.",
    "creator_use_default": "Usar padrão",
    "creator_default": "padrão",
    "creator_desktop_integration": "Integração com área de trabalho",
    "creator_file_protocol_associations_and_wine_special_desktop_fold": "Associações de arquivo/protocolo e mapeamentos de pastas especiais do Wine.",
    "creator_integration_can_affect_user_system_behavior": "Integração pode afetar o sistema do usuário",
    "creator_mime_protocol_associations_and_special_folders_can_chang": "Associações MIME/protocolo e pastas especiais podem alterar integração com desktop. Prefira configurar apenas o necessário para o jogo.",
    "creator_desktop_integration_general": "Integração com desktop (geral)",
    "creator_controls_wine_integration_with_the_linux_shell_desktop": "Controla integração do Wine com shell/desktop do Linux.",
    "creator_mime_types_file_protocol_associations": "Tipos MIME (associações de arquivo e protocolo)",
    "creator_equivalent_to_manage_file_and_protocol_associations": "Equivalente a \"Manage file and protocol associations\".",
    "creator_special_folders": "Pastas especiais",
    "creator_add_folder_shortcut_mappings_for_wine_optional_override": "Adicione mapeamentos de pasta e atalho para o Wine (override opcional).",
    "creator_add_folder": "Adicionar pasta",
    "creator_add_wine_special_folder": "Adicionar pasta especial do Wine",
    "creator_set_folder_type_shortcut_name_and_linux_path": "Defina o tipo da pasta, nome do atalho e caminho Linux.",
    "creator_shortcut_name_in_wine": "Nome do atalho no Wine",
    "creator_prefer_generic_paths_without_a_fixed_username_when_possi": "Prefira caminhos genéricos (sem nome de usuário fixo), quando possível.",
    "creator_no_special_folder_added": "Nenhuma pasta especial adicionada.",
    "creator_shortcut": "Atalho",
    "creator_linux_path": "Caminho Linux",
    "creator_drives": "Unidades",
    "creator_additional_wine_drives_as_overrides_c_and_z_usually_alre": "Unidades adicionais do Wine como overrides. C: e Z geralmente já existem no prefixo padrão.",
    "creator_wine_drives_require_care": "Unidades do Wine exigem cuidado",
    "creator_c_and_z_usually_already_exist_in_the_default_prefix_add": "C: e Z: normalmente já existem no prefixo padrão. Adicione novas unidades apenas quando o jogo realmente depender disso e prefira caminhos Linux genéricos.",
    "creator_usually_points_to_drive_c_internal_prefix_path": "normalmente aponta para drive_c (interno do prefixo).",
    "creator_usually_exposes_the_linux_filesystem_root_for_compatibil": "geralmente expõe a raiz do filesystem Linux por compatibilidade.",
    "creator_restore_shown_default_z": "Restaurar padrão exibido (Z:)",
    "creator_add_drive": "Adicionar unidade",
    "creator_add_wine_drive": "Adicionar unidade do Wine",
    "creator_choose_an_available_letter_and_configure_drive_metadata": "Escolha uma letra disponível e configure os metadados da unidade.",
    "creator_label_optional": "Rótulo (opcional)",
    "creator_serial_optional": "Serial (opcional)",
    "creator_use_a_generic_linux_directory_when_possible_avoid_user_s": "Use um diretório Linux genérico quando possível (evite paths fixos com nome de usuário).",
    "creator_that_drive_letter_is_already_in_use": "Essa letra de unidade já está em uso.",
    "creator_no_additional_drive_configured": "Nenhuma unidade adicional configurada.",
    "creator_letter": "Letra",
    "creator_label": "Rótulo",
    "creator_serial": "Serial",
    "creator_audio": "Áudio",
    "creator_additional_audio_settings_from_winecfg_runtime_defaults": "Configurações adicionais de áudio do winecfg. O padrão do runtime continua válido se nada for alterado.",
    "creator_audio_change_only_if_needed": "Áudio: altere só se precisar",
    "creator_forcing_an_audio_backend_can_fix_compatibility_but_may_w": "Forçar backend de áudio pode resolver compatibilidade, mas também pode piorar em outros hosts. O padrão do runtime costuma ser a opção mais portátil.",
    "creator_audio_driver": "Driver de áudio",
    "creator_select_the_preferred_backend_runtime_default_keeps_wine": "Selecione o backend preferido. \"Padrão do runtime\" mantém o comportamento padrão do Wine.",
    "creator_wrapper_commands": "Comandos de wrapper",
    "creator_commands_executed_before_the_main_runtime_e_g_gamescope": "Comandos executados antes do runtime principal (ex.: gamescope, gamemoderun, mangohud).",
    "creator_no_wrapper_command_added": "Nenhum comando de wrapper adicionado.",
    "creator_executable": "Executável",
    "creator_arguments": "Argumentos",
    "creator_remove_wrapper": "Remover wrapper",
    "creator_add_wrapper": "Adicionar wrapper",
    "creator_set_policy_executable_and_wrapper_arguments": "Defina política, executável e argumentos do wrapper.",
    "creator_executable_e_g_gamescope": "Executável (ex.: gamescope)",
    "creator_args_e_g_w_1920_h_1080": "Args (ex.: -w 1920 -h 1080)",
    "creator_environment_variables": "Variáveis de ambiente",
    "creator_applied_at_launch_protected_keys_are_ignored_by_runtime": "Aplicadas no launch (chaves protegidas são ignoradas pelo runtime).",
    "creator_add_variable": "Adicionar variável",
    "creator_no_environment_variable_added": "Nenhuma variável de ambiente adicionada.",
    "creator_variable": "Variável",
    "creator_runtime_protected_keys": "Chaves protegidas pelo runtime",
    "creator_the_keys_below_are_reserved_if_added_above_they_will_be": "As chaves abaixo são reservadas. Se forem adicionadas na lista acima, serão ignoradas pelo orquestrador.",
    "creator_pre_launch_script_bash": "Script antes de iniciar o jogo (bash)",
    "creator_executed_before_starting_the_game": "Executado antes de iniciar o jogo.",
    "creator_post_launch_script_bash": "Script após fechar o jogo (bash)",
    "creator_executed_after_the_game_exits": "Executado após o jogo ser encerrado.",
    "creator_local_scripts_mvp": "Scripts locais (MVP)",
    "creator_scripts_accept_bash_only_and_local_execution_in_the_mvp": "Scripts aceitam apenas bash e execução local no MVP.",
    "creator_scripts_are_not_sent_to_the_community_api_use_trusted_co": "Scripts não são enviados para a API comunitária. Use apenas comandos confiáveis.",
    "creator_configuration_summary": "Resumo da configuração",
    "creator_quick_view_of_how_many_items_were_configured_in_each_sec": "Visão rápida da quantidade de itens configurados em cada seção.",
    "creator_launch_arguments_2": "Argumentos de inicialização",
    "creator_windows_registry": "Registro do Windows",
    "creator_mounts": "Montagens",
    "creator_wrappers": "Wrappers",
    "creator_configuration_preview_json": "Pré-visualização da configuração (JSON)",
    "creator_last_action_result": "Resultado da última ação",
    "creator_back": "Retornar",
    "creator_next": "Avançar",
    "creator_mandatory_enabled": "Obrigatório: Ativado",
    "creator_mandatory_disabled": "Obrigatório: Desativado",
    "creator_optional_enabled": "Opcional: Ativado",
    "creator_optional_disabled": "Opcional: Desativado",
    "creator_runtime_default": "Padrão do runtime",
    "creator_integer_scaling": "Escala Inteira",
    "creator_stretch_image": "Esticar imagem",
    "creator_fullscreen": "Tela cheia",
    "creator_borderless": "Sem borda",
    "creator_windowed_2": "Janela",
    "creator_select_an_executable_before_hashing": "Selecione um executável antes de calcular hash.",
    "creator_hashing_requires_an_absolute_path_in_browser_lan_mode_us": "Calcular hash requer caminho absoluto. No modo navegador (LAN), use o app Tauri local.",
    "creator_select_game_executable": "Selecionar executável do jogo",
    "creator_select_a_valid_windows_launcher_exe_bat_cmd_com": "Selecione um executável Windows válido (.exe, .bat, .cmd, .com).",
    "creator_select_reg_file": "Selecionar arquivo .reg",
    "creator_select_game_root_folder": "Selecionar pasta raiz do jogo",
    "creator_the_selected_game_root_must_contain_the_main_executable": "A pasta raiz escolhida deve conter o executável principal.",
    "creator_select_required_file": "Selecionar arquivo obrigatório",
    "creator_selected_file_must_be_inside_the_game_root_folder": "O arquivo selecionado precisa estar dentro da pasta raiz do jogo.",
    "creator_select_folder_to_mount": "Selecionar pasta para montar",
    "creator_selected_folder_must_be_inside_game_root_folder": "A pasta selecionada precisa estar dentro da pasta raiz do jogo.",
    "creator_icon_extraction_will_be_wired_to_backend_in_the_next_fun": "Extração de ícone será conectada ao backend na próxima etapa funcional.",
    "creator_type_at_least_2_characters_and_select_a_valid_catalog_ve": "Digite ao menos 2 caracteres e selecione um verbo válido do catálogo.",
    "creator_winetricks_catalog_loaded_count": "Catálogo Winetricks carregado ({count} itens).",
    "creator_failed_to_load_winetricks_catalog_error": "Falha ao carregar catálogo Winetricks: {error}",
    "creator_registry_import_warning_suffix_count": " ({count} aviso(s) ao importar)",
    "creator_imported_registry_keys_from_reg_file": "Importadas {count} chave(s) de registro do arquivo .reg{warningSuffix}.",
    "creator_failed_to_import_reg_file_error": "Falha ao importar arquivo .reg: {error}",
    "creator_failed_to_list_folders_error": "Falha ao listar pastas: {error}",
    "creator_game_root_hint_invalid_exe_outside_root": "Inválido: o executável principal precisa estar dentro da pasta raiz.",
    "creator_game_root_hint_manual_override": "Pasta raiz alterada manualmente.",
    "creator_game_root_hint_auto": "Pasta raiz automática baseada no executável.",
    "creator_executable_lives_in_relative_path": "Executável fica em: ./{path}",
  },
  "en-US": {
    "creator_label_game": "Game",
    "creator_label_runtime": "Runtime",
    "creator_enhancements": "Enhancements",
    "creator_dependencies": "Dependencies",
    "creator_launch_and_environment": "Launch and Environment",
    "creator_label_scripts": "Scripts",
    "creator_review_and_generate": "Review and Generate",
    "creator_runtime_default_do_not_override": "Runtime default (do not override)",
    "creator_desktop": "Desktop",
    "creator_documents": "Documents",
    "creator_downloads": "Downloads",
    "creator_music": "Music",
    "creator_pictures": "Pictures",
    "creator_videos": "Videos",
    "creator_auto_detect": "Auto detect",
    "creator_local_hard_disk": "Local hard disk",
    "creator_network_share": "Network share",
    "creator_floppy_disk": "Floppy disk",
    "creator_cd_rom": "CD-ROM",
    "creator_proton_version": "Proton version",
    "creator_wine_version": "Wine version",
    "creator_preferred_runtime_version": "Preferred runtime version",
    "creator_target_proton_version_used_by_the_orchestrator_when_pref": "Target Proton version used by the orchestrator when preference is Proton.",
    "creator_expected_wine_version_identifier_when_preference_is_wine": "Expected Wine version/identifier when preference is Wine.",
    "creator_preferred_runtime_version_when_auto_mode_picks_proton_wi": "Preferred runtime version when Auto mode picks Proton/Wine based on availability.",
    "creator_importing_reg_requires_an_absolute_path_in_browser_lan_m": "Importing .reg requires an absolute path. In browser/LAN mode, use the local Tauri app.",
    "creator_mounted_folder_browser_requires_an_absolute_game_root_pa": "Mounted-folder browser requires an absolute game root path. Use the local Tauri app.",
    "creator_select_an_executable_first_to_define_the_game_folder": "Select an executable first to define the game folder.",
    "creator_in_browser_lan_mode_the_mini_folder_browser_cannot_acces": "In browser/LAN mode, the mini folder browser cannot access the filesystem. Use the local Tauri app.",
    "creator_language": "Language",
    "creator_dark": "Dark",
    "creator_light": "Light",
    "creator_system": "System",
    "creator_theme": "Theme",
    "creator_label_enabled": "Enabled",
    "creator_label_disabled": "Disabled",
    "creator_label_mandatory": "Mandatory",
    "creator_use_wine_default": "Use Wine default",
    "creator_label_actions": "Actions",
    "creator_label_action": "Action",
    "creator_label_add": "Add",
    "creator_add_item": "Add item",
    "creator_enter_a_value_and_confirm_to_add_it_to_the_list": "Enter a value and confirm to add it to the list.",
    "creator_fill_in_key_and_value_to_add_a_new_row": "Fill in key and value to add a new row.",
    "creator_choose_file": "Choose file",
    "creator_select_a_file_to_fill_this_field_automatically": "Select a file to fill this field automatically.",
    "creator_label_cancel": "Cancel",
    "creator_label_confirm": "Confirm",
    "creator_label_remove": "Remove",
    "creator_no_item_added": "No item added.",
    "creator_key": "Key",
    "creator_value": "Value",
    "creator_open_menu": "Open menu",
    "creator_step": "Step",
    "creator_game_name": "Game name",
    "creator_name_shown_in_splash_and_local_database": "Name shown in splash and local database.",
    "creator_main_executable_exe": "Main executable (.exe)",
    "creator_use_picker_to_select_the_real_game_executable": "Use picker to select the real game executable.",
    "creator_select_file": "Select file",
    "creator_game_root_folder": "Game root folder",
    "creator_defaults_to_the_main_executable_folder_but_can_be_change": "Defaults to the main executable folder, but can be changed if the .exe is in a subfolder.",
    "creator_choose_another": "Choose another",
    "creator_choose_game_root_folder": "Choose game root folder",
    "creator_the_game_root_must_be_an_ancestor_of_the_folder_that_con": "The game root must be an ancestor of the folder that contains the main executable.",
    "creator_this_guided_flow_requires_an_absolute_executable_path_lo": "This guided flow requires an absolute executable path (local Tauri mode).",
    "creator_use_system_picker": "Use system picker",
    "creator_executable_folder_breadcrumb": "Executable folder breadcrumb",
    "creator_executable_path": "Executable path",
    "creator_select_which_ancestor_level_should_be_the_game_root": "Select which ancestor level should be the game root.",
    "creator_same_directory_as_executable_automatic": "Same directory as executable (automatic)",
    "creator_close": "Close",
    "creator_sha_256_hash": "SHA-256 hash",
    "creator_main_identifier_for_profile_and_per_game_prefix": "Main identifier for profile and per-game prefix.",
    "creator_final_prefix_path": "Final prefix path",
    "creator_automatically_calculated_from_executable_hash": "Automatically calculated from executable hash.",
    "creator_prefix_path_copied": "Prefix path copied.",
    "creator_failed_to_copy_to_clipboard": "Failed to copy to clipboard.",
    "creator_copy": "Copy",
    "creator_extracted_icon": "Extracted icon",
    "creator_game_icon_preview_for_easier_visual_identification": "Game icon preview for easier visual identification.",
    "creator_visual_is_ready_real_extraction_will_be_wired_to_backend": "Visual is ready. Real extraction will be wired to backend next.",
    "creator_no_extracted_icon": "No extracted icon",
    "creator_extract_icon": "Extract icon",
    "creator_launch_arguments": "Launch arguments",
    "creator_extra_arguments_passed_to_game_executable": "Extra arguments passed to game executable.",
    "creator_windowed": "-windowed",
    "creator_add_argument": "Add argument",
    "creator_no_launch_argument_added": "No launch argument added.",
    "creator_argument": "Argument",
    "creator_required_files": "Required files",
    "creator_if_any_listed_file_is_missing_from_the_game_folder_start": "If any listed file is missing from the game folder, startup is blocked.",
    "creator_data_core_dll": "./data/core.dll",
    "creator_add_file": "Add file",
    "creator_pick_file_from_game_folder": "Pick file from game folder",
    "creator_no_file_added": "No file added.",
    "creator_relative_file": "Relative file",
    "creator_mounted_folders": "Mounted folders",
    "creator_maps_a_folder_inside_the_game_to_a_windows_target_inside": "Maps a folder inside the game to a Windows target inside the prefix (e.g. saves under Documents).",
    "creator_no_mount_added": "No mount added.",
    "creator_relative_source": "Relative source",
    "creator_windows_target": "Windows target",
    "creator_create_source": "Create source",
    "creator_yes": "Yes",
    "creator_no": "No",
    "creator_folder": "Folder",
    "creator_remove_mount": "Remove mount",
    "creator_add_mount": "Add mount",
    "creator_set_relative_source_and_windows_target_to_create_the_mou": "Set relative source and Windows target to create the mount.",
    "creator_relative_source_e_g_save": "Relative source (e.g. save)",
    "creator_browse_folders": "Browse folders",
    "creator_windows_target_c_users": "Windows target (C:\\users\\...)",
    "creator_create_source_if_missing": "Create source if missing",
    "creator_select_folder_inside_game": "Select folder inside game",
    "creator_mini_browser_restricted_to_the_game_root_to_prevent_moun": "Mini browser restricted to the game root to prevent mounts outside the project.",
    "creator_current_path": "Current path",
    "creator_folder_breadcrumb": "Folder breadcrumb",
    "creator_loading_folders": "Loading folders...",
    "creator_no_subfolder_found": "No subfolder found.",
    "creator_select_this_folder": "Select this folder",
    "creator_use_this_folder": "Use this folder",
    "creator_general_runtime_preference": "General runtime preference",
    "creator_macro_priority_among_auto_proton_and_wine": "Macro priority among Auto, Proton and Wine.",
    "creator_required_version": "Required version",
    "creator_when_enabled_requires_the_configured_runtime_version_to": "When enabled, requires the configured runtime version to launch.",
    "creator_auto_update": "Auto update",
    "creator_updates_runtime_metadata_when_applicable_before_launchin": "Updates runtime metadata when applicable before launching.",
    "creator_enables_synchronization_optimizations_in_runtime": "Enables synchronization optimizations in runtime.",
    "creator_enables_fsync_optimizations_when_supported": "Enables FSYNC optimizations when supported.",
    "creator_controls_umu_run_usage_according_to_enforcement_policy": "Controls umu-run usage according to enforcement policy.",
    "creator_steam_runtime": "Steam Runtime",
    "creator_defines_whether_steam_runtime_is_mandatory_optional_or_b": "Defines whether steam runtime is mandatory, optional or blocked.",
    "creator_policy_for_local_easy_anticheat_runtime": "Policy for local Easy AntiCheat runtime.",
    "creator_policy_for_local_battleeye_runtime": "Policy for local BattleEye runtime.",
    "creator_defines_gamescope_policy_and_syncs_with_requirements_gam": "Defines gamescope policy and syncs with requirements.gamescope.",
    "creator_gamescope_is_disabled_enable_it_to_configure_resolution": "Gamescope is disabled. Enable it to configure resolution, upscale and window mode.",
    "creator_upscale_method": "Upscale method",
    "creator_method_used_by_gamescope_for_upscaling": "Method used by gamescope for upscaling.",
    "creator_window_type": "Window type",
    "creator_defines_gamescope_window_behavior": "Defines gamescope window behavior.",
    "creator_game_resolution": "Game resolution",
    "creator_game_render_resolution_width_x_height": "Game render resolution (width x height).",
    "creator_display_resolution": "Display resolution",
    "creator_final_gamescope_output_resolution_width_x_height": "Final gamescope output resolution (width x height).",
    "creator_auto": "Auto",
    "creator_use_monitor_resolution": "Use monitor resolution",
    "creator_enable_fps_limiter": "Enable FPS limiter",
    "creator_enables_gamescope_fps_limiter": "Enables gamescope FPS limiter.",
    "creator_force_grab_cursor": "Force grab cursor",
    "creator_forces_relative_mouse_mode_to_avoid_focus_loss": "Forces relative mouse mode to avoid focus loss.",
    "creator_fps_limit": "FPS limit",
    "creator_fps_limit_when_game_is_focused": "FPS limit when game is focused.",
    "creator_fps_limit_without_focus": "FPS limit without focus",
    "creator_fps_limit_when_game_loses_focus": "FPS limit when game loses focus.",
    "creator_gamescope_additional_options": "Gamescope additional options",
    "creator_add_extra_flags_that_will_be_appended_to_the_gamescope_c": "Add extra flags that will be appended to the gamescope command.",
    "creator_prefer_vk_device_1002_73bf": "--prefer-vk-device 1002:73bf",
    "creator_add_option": "Add option",
    "creator_defines_gamemode_policy": "Defines gamemode policy.",
    "creator_defines_mangohud_policy": "Defines MangoHud policy.",
    "creator_policy_for_enabling_wine_wayland": "Policy for enabling Wine-Wayland.",
    "creator_policy_for_hdr_depends_on_wine_wayland": "Policy for HDR (depends on Wine-Wayland).",
    "creator_controls_automatic_dxvk_nvapi_setup": "Controls automatic DXVK-NVAPI setup.",
    "creator_controls_mandatory_usage_of_wine_staging_runtime": "Controls mandatory usage of Wine staging runtime.",
    "creator_use_dedicated_gpu": "Use dedicated GPU",
    "creator_exports_prime_render_offload_variables_to_try_using_the": "Exports PRIME render offload variables to try using the dedicated GPU on hybrid systems.",
    "creator_enabled_automatically_when_at_least_one_verb_is_configur": "Enabled automatically when at least one verb is configured. Use search to add verbs from the catalog.",
    "creator_remove_verb": "Remove verb",
    "creator_failed_to_load_winetricks_catalog": "Failed to load winetricks catalog",
    "creator_search_and_add_verbs_e_g_vcrun_corefonts": "Search and add verbs (e.g. vcrun, corefonts)",
    "creator_the_local_remote_catalog_could_not_be_loaded_you_can_sti": "The local/remote catalog could not be loaded. You can still refresh the catalog manually.",
    "creator_type_at_least_2_characters_to_search_verbs_in_the_catalo": "Type at least 2 characters to search verbs in the catalog.",
    "creator_no_items_found": "No items found.",
    "creator_loading_catalog_in_background": "Loading catalog in background...",
    "creator_loading": "Loading...",
    "creator_refresh_catalog": "Refresh catalog",
    "creator_source": "Source:",
    "creator_catalog": "Catalog:",
    "creator_registry_keys": "Registry keys",
    "creator_table_of_keys_applied_to_prefix_after_bootstrap": "Table of keys applied to prefix after bootstrap.",
    "creator_no_key_added": "No key added.",
    "creator_path": "Path",
    "creator_name": "Name",
    "creator_type": "Type",
    "creator_remove_key": "Remove key",
    "creator_add_key": "Add key",
    "creator_add_registry_key": "Add registry key",
    "creator_fill_fields_and_confirm_to_add_row": "Fill fields and confirm to add row.",
    "creator_path_hkcu": "Path (HKCU\\...)",
    "creator_key_name": "Key name",
    "creator_type_reg_sz": "Type (REG_SZ)",
    "creator_add_from_file_reg": "Add from file (.reg)",
    "creator_reg_import_warnings": ".reg import warnings",
    "creator_some_lines_were_ignored_or_imported_with_fallback_review": "Some lines were ignored or imported with fallback. Review the warnings below.",
    "creator_extra_system_dependencies": "Extra system dependencies",
    "creator_additional_dependencies_validated_in_doctor_by_command_e": "Additional dependencies validated in doctor by command/env/path.",
    "creator_command": "Command",
    "creator_env_vars": "Env vars",
    "creator_default_paths": "Default paths",
    "creator_unnamed": "Unnamed",
    "creator_remove_dependency": "Remove dependency",
    "creator_no_extra_dependency_added": "No extra dependency added.",
    "creator_add_dependency": "Add dependency",
    "creator_add_extra_system_dependency": "Add extra system dependency",
    "creator_define_how_doctor_can_detect_this_dependency_command_env": "Define how doctor can detect this dependency (command, env vars and default paths).",
    "creator_dependency_name": "Dependency name",
    "creator_terminal_command_e_g_mangohud": "Terminal command (e.g. mangohud)",
    "creator_environment_vars_comma_separated": "Environment vars (comma-separated)",
    "creator_default_paths_comma_separated": "Default paths (comma-separated)",
    "creator_winecfg_overrides_do_not_replace_everything": "Winecfg overrides (do not replace everything)",
    "creator_settings_in_this_tab_are_additive_overrides_on_top_of_wi": "Settings in this tab are additive overrides on top of Wine/prefix defaults. If you keep \"Wine default\", the orchestrator does not force that item.",
    "creator_dll_overrides": "DLL overrides",
    "creator_configures_per_dll_overrides_such_as_native_builtin": "Configures per-DLL overrides such as native/builtin.",
    "creator_no_override_added": "No override added.",
    "creator_dll": "DLL",
    "creator_mode": "Mode",
    "creator_add_dll_override": "Add DLL override",
    "creator_set_the_dll_name_and_override_mode": "Set the DLL name and override mode.",
    "creator_windows_version_winecfg": "Windows version (winecfg)",
    "creator_optional_override_for_the_windows_version_reported_by_th": "Optional override for the Windows version reported by the prefix. If unset, runtime/prefix defaults are kept.",
    "creator_graphics": "Graphics",
    "creator_equivalent_to_the_graphics_tab_in_winecfg_everything_her": "Equivalent to the Graphics tab in winecfg. Everything here is an additive override to prefix defaults.",
    "creator_graphics_incremental_overrides": "Graphics = incremental overrides",
    "creator_these_items_do_not_recreate_the_prefix_they_only_add_win": "These items do not recreate the prefix. They only add winecfg behavior overrides on top of what already exists in the current prefix.",
    "creator_automatically_capture_mouse_in_fullscreen_windows": "Automatically capture mouse in fullscreen windows",
    "creator_equivalent_to_winecfg_auto_capture_mouse_option": "Equivalent to winecfg auto-capture mouse option.",
    "creator_allow_the_window_manager_to_decorate_windows": "Allow the window manager to decorate windows",
    "creator_controls_window_decorations_managed_by_the_wm": "Controls window decorations managed by the WM.",
    "creator_allow_the_window_manager_to_control_windows": "Allow the window manager to control windows",
    "creator_lets_the_wm_control_window_position_focus_state": "Lets the WM control window position/focus/state.",
    "creator_emulate_a_virtual_desktop": "Emulate a virtual desktop",
    "creator_when_enabled_the_game_runs_inside_a_wine_virtual_desktop": "When enabled, the game runs inside a Wine virtual desktop.",
    "creator_virtual_desktop_size": "Virtual desktop size",
    "creator_set_width_x_height_e_g_1280_x_720": "Set width x height (e.g. 1280 x 720).",
    "creator_screen_resolution_dpi": "Screen resolution (DPI)",
    "creator_slider_from_96_dpi_to_480_dpi_if_unset_wine_default_is_u": "Slider from 96 DPI to 480 DPI. If unset, Wine default is used.",
    "creator_use_default": "Use default",
    "creator_default": "default",
    "creator_desktop_integration": "Desktop integration",
    "creator_file_protocol_associations_and_wine_special_desktop_fold": "File/protocol associations and Wine special desktop folder mappings.",
    "creator_integration_can_affect_user_system_behavior": "Integration can affect user system behavior",
    "creator_mime_protocol_associations_and_special_folders_can_chang": "MIME/protocol associations and special folders can change desktop integration behavior. Configure only what the game needs.",
    "creator_desktop_integration_general": "Desktop integration (general)",
    "creator_controls_wine_integration_with_the_linux_shell_desktop": "Controls Wine integration with the Linux shell/desktop.",
    "creator_mime_types_file_protocol_associations": "MIME types (file/protocol associations)",
    "creator_equivalent_to_manage_file_and_protocol_associations": "Equivalent to \"Manage file and protocol associations\".",
    "creator_special_folders": "Special folders",
    "creator_add_folder_shortcut_mappings_for_wine_optional_override": "Add folder + shortcut mappings for Wine (optional override).",
    "creator_add_folder": "Add folder",
    "creator_add_wine_special_folder": "Add Wine special folder",
    "creator_set_folder_type_shortcut_name_and_linux_path": "Set folder type, shortcut name and Linux path.",
    "creator_shortcut_name_in_wine": "Shortcut name in Wine",
    "creator_prefer_generic_paths_without_a_fixed_username_when_possi": "Prefer generic paths (without a fixed username) when possible.",
    "creator_no_special_folder_added": "No special folder added.",
    "creator_shortcut": "Shortcut",
    "creator_linux_path": "Linux path",
    "creator_drives": "Drives",
    "creator_additional_wine_drives_as_overrides_c_and_z_usually_alre": "Additional Wine drives as overrides. C: and Z: usually already exist in the default prefix.",
    "creator_wine_drives_require_care": "Wine drives require care",
    "creator_c_and_z_usually_already_exist_in_the_default_prefix_add": "C: and Z: usually already exist in the default prefix. Add new drives only when the game really depends on it and prefer generic Linux paths.",
    "creator_usually_points_to_drive_c_internal_prefix_path": "usually points to drive_c (internal prefix path).",
    "creator_usually_exposes_the_linux_filesystem_root_for_compatibil": "usually exposes the Linux filesystem root for compatibility.",
    "creator_restore_shown_default_z": "Restore shown default (Z:)",
    "creator_add_drive": "Add drive",
    "creator_add_wine_drive": "Add Wine drive",
    "creator_choose_an_available_letter_and_configure_drive_metadata": "Choose an available letter and configure drive metadata.",
    "creator_label_optional": "Label (optional)",
    "creator_serial_optional": "Serial (optional)",
    "creator_use_a_generic_linux_directory_when_possible_avoid_user_s": "Use a generic Linux directory when possible (avoid user-specific absolute paths).",
    "creator_that_drive_letter_is_already_in_use": "That drive letter is already in use.",
    "creator_no_additional_drive_configured": "No additional drive configured.",
    "creator_letter": "Letter",
    "creator_label": "Label",
    "creator_serial": "Serial",
    "creator_audio": "Audio",
    "creator_additional_audio_settings_from_winecfg_runtime_defaults": "Additional audio settings from winecfg. Runtime defaults remain valid if nothing is changed.",
    "creator_audio_change_only_if_needed": "Audio: change only if needed",
    "creator_forcing_an_audio_backend_can_fix_compatibility_but_may_w": "Forcing an audio backend can fix compatibility, but may worsen behavior on other hosts. Runtime default is usually the most portable option.",
    "creator_audio_driver": "Audio driver",
    "creator_select_the_preferred_backend_runtime_default_keeps_wine": "Select the preferred backend. \"Runtime default\" keeps Wine default behavior.",
    "creator_wrapper_commands": "Wrapper commands",
    "creator_commands_executed_before_the_main_runtime_e_g_gamescope": "Commands executed before the main runtime (e.g. gamescope, gamemoderun, mangohud).",
    "creator_no_wrapper_command_added": "No wrapper command added.",
    "creator_executable": "Executable",
    "creator_arguments": "Arguments",
    "creator_remove_wrapper": "Remove wrapper",
    "creator_add_wrapper": "Add wrapper",
    "creator_set_policy_executable_and_wrapper_arguments": "Set policy, executable and wrapper arguments.",
    "creator_executable_e_g_gamescope": "Executable (e.g. gamescope)",
    "creator_args_e_g_w_1920_h_1080": "Args (e.g. -w 1920 -h 1080)",
    "creator_environment_variables": "Environment variables",
    "creator_applied_at_launch_protected_keys_are_ignored_by_runtime": "Applied at launch (protected keys are ignored by runtime).",
    "creator_add_variable": "Add variable",
    "creator_no_environment_variable_added": "No environment variable added.",
    "creator_variable": "Variable",
    "creator_runtime_protected_keys": "Runtime-protected keys",
    "creator_the_keys_below_are_reserved_if_added_above_they_will_be": "The keys below are reserved. If added above, they will be ignored by the orchestrator.",
    "creator_pre_launch_script_bash": "Pre-launch script (bash)",
    "creator_executed_before_starting_the_game": "Executed before starting the game.",
    "creator_post_launch_script_bash": "Post-launch script (bash)",
    "creator_executed_after_the_game_exits": "Executed after the game exits.",
    "creator_local_scripts_mvp": "Local scripts (MVP)",
    "creator_scripts_accept_bash_only_and_local_execution_in_the_mvp": "Scripts accept bash only and local execution in the MVP.",
    "creator_scripts_are_not_sent_to_the_community_api_use_trusted_co": "Scripts are not sent to the community API. Use trusted commands only.",
    "creator_configuration_summary": "Configuration summary",
    "creator_quick_view_of_how_many_items_were_configured_in_each_sec": "Quick view of how many items were configured in each section.",
    "creator_launch_arguments_2": "Launch arguments",
    "creator_windows_registry": "Windows Registry",
    "creator_mounts": "Mounts",
    "creator_wrappers": "Wrappers",
    "creator_configuration_preview_json": "Configuration preview (JSON)",
    "creator_last_action_result": "Last action result",
    "creator_back": "Back",
    "creator_next": "Next",
    "creator_mandatory_enabled": "Mandatory: Enabled",
    "creator_mandatory_disabled": "Mandatory: Disabled",
    "creator_optional_enabled": "Optional: Enabled",
    "creator_optional_disabled": "Optional: Disabled",
    "creator_runtime_default": "Runtime default",
    "creator_integer_scaling": "Integer Scaling",
    "creator_stretch_image": "Stretch image",
    "creator_fullscreen": "Fullscreen",
    "creator_borderless": "Borderless",
    "creator_windowed_2": "Windowed",
    "creator_select_an_executable_before_hashing": "Select an executable before hashing.",
    "creator_hashing_requires_an_absolute_path_in_browser_lan_mode_us": "Hashing requires an absolute path. In browser/LAN mode, use the local Tauri app.",
    "creator_select_game_executable": "Select game executable",
    "creator_select_a_valid_windows_launcher_exe_bat_cmd_com": "Select a valid Windows launcher (.exe, .bat, .cmd, .com).",
    "creator_select_reg_file": "Select .reg file",
    "creator_select_game_root_folder": "Select game root folder",
    "creator_the_selected_game_root_must_contain_the_main_executable": "The selected game root must contain the main executable.",
    "creator_select_required_file": "Select required file",
    "creator_selected_file_must_be_inside_the_game_root_folder": "Selected file must be inside the game root folder.",
    "creator_select_folder_to_mount": "Select folder to mount",
    "creator_selected_folder_must_be_inside_game_root_folder": "Selected folder must be inside game root folder.",
    "creator_icon_extraction_will_be_wired_to_backend_in_the_next_fun": "Icon extraction will be wired to backend in the next functional step.",
    "creator_type_at_least_2_characters_and_select_a_valid_catalog_ve": "Type at least 2 characters and select a valid catalog verb.",
    "creator_winetricks_catalog_loaded_count": "Winetricks catalog loaded ({count} items).",
    "creator_failed_to_load_winetricks_catalog_error": "Failed to load Winetricks catalog: {error}",
    "creator_registry_import_warning_suffix_count": " ({count} warning(s) while importing)",
    "creator_imported_registry_keys_from_reg_file": "Imported {count} registry key(s) from .reg file{warningSuffix}.",
    "creator_failed_to_import_reg_file_error": "Failed to import .reg file: {error}",
    "creator_failed_to_list_folders_error": "Failed to list folders: {error}",
    "creator_game_root_hint_invalid_exe_outside_root": "Invalid: the main executable must be inside the game root.",
    "creator_game_root_hint_manual_override": "Game root manually overridden.",
    "creator_game_root_hint_auto": "Automatic game root based on the executable.",
    "creator_executable_lives_in_relative_path": "Executable lives in: ./{path}",
  }
} as const

export type CreatorCopyKey = keyof typeof creatorMessages['pt-BR']

export function creatorTranslate(locale: Locale, key: CreatorCopyKey): string {
  return creatorMessages[locale][key] ?? creatorMessages['en-US'][key] ?? key
}

export function creatorFormat(
  locale: Locale,
  key: CreatorCopyKey,
  params: Record<string, string | number>
): string {
  const template = creatorTranslate(locale, key)
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? `{${name}}`))
}
