export const luthierMessagesEnUS = {
    "luthier_label_game": "Game",
    "luthier_label_game_files_and_launch": "Files & Launch",
    "luthier_label_runtime": "Runtime",
    "luthier_enhancements": "Enhancements",
    "luthier_dependencies": "Dependencies",
    "luthier_launch_and_environment": "Launch and Environment",
    "luthier_label_scripts": "Scripts",
    "luthier_review_and_generate": "Review and Generate",
    "luthier_summary_game_root": "Game root",
    "luthier_summary_strict_proton_version": "Strict Proton version",
    "luthier_summary_windows_version": "Windows",
    "luthier_summary_virtual_desktop": "Virtual desktop",
    "luthier_summary_mime_protocols": "MIME/Protocols",
    "luthier_runtime_default_do_not_override": "Runtime default (do not override)",
    "luthier_desktop": "Desktop",
    "luthier_documents": "Documents",
    "luthier_downloads": "Downloads",
    "luthier_music": "Music",
    "luthier_pictures": "Pictures",
    "luthier_videos": "Videos",
    "luthier_auto_detect": "Auto detect",
    "luthier_local_hard_disk": "Local hard disk",
    "luthier_network_share": "Network share",
    "luthier_floppy_disk": "Floppy disk",
    "luthier_cd_rom": "CD-ROM",
    "luthier_proton_version": "Proton version",
    "luthier_wine_version": "Wine version",
    "luthier_preferred_runtime_version": "Preferred runtime version",
    "luthier_target_proton_version_used_by_the_orchestrator_when_pref": "Target Proton version used by the orchestrator when preference is Proton.",
    "luthier_expected_wine_version_identifier_when_preference_is_wine": "Expected Wine version/identifier when preference is Wine.",
    "luthier_preferred_runtime_version_when_auto_mode_picks_proton_wi": "Preferred runtime version when Auto mode picks Proton/Wine based on availability.",
    "luthier_importing_reg_requires_an_absolute_path_in_browser_lan_m": "Importing .reg requires an absolute path. In browser/LAN mode, use the local Tauri app.",
    "luthier_mounted_folder_browser_requires_an_absolute_game_root_pa": "Mounted-folder browser requires an absolute game root path. Use the local Tauri app.",
    "luthier_required_file_browser_requires_an_absolute_game_root_pat": "Required-file browser requires an absolute game root path. Use the local Tauri app.",
    "luthier_select_an_executable_first_to_define_the_game_folder": "Select an executable first to define the game folder.",
    "luthier_in_browser_lan_mode_the_mini_folder_browser_cannot_acces": "In browser/LAN mode, the mini folder browser cannot access the filesystem. Use the local Tauri app.",
    "luthier_in_browser_lan_mode_the_mini_file_browser_cannot_access_": "In browser/LAN mode, the mini file browser cannot access the filesystem. Use the local Tauri app.",
    "luthier_failed_to_list_files_error": "Failed to list files: {error}",
    "luthier_language": "Language",
    "luthier_dark": "Dark",
    "luthier_light": "Light",
    "luthier_system": "System",
    "luthier_theme": "Theme",
    "luthier_label_enabled": "Enabled",
    "luthier_label_disabled": "Disabled",
    "luthier_label_mandatory": "Mandatory",
    "luthier_undo": "Undo",
    "luthier_registry_import_undone": "Registry import undone.",
    "luthier_use_wine_default": "Default",
    "luthier_label_actions": "Actions",
    "luthier_label_action": "Action",
    "luthier_label_add": "Add",
    "luthier_add_item": "Add item",
    "luthier_enter_a_value_and_confirm_to_add_it_to_the_list": "Enter a value and confirm to add it to the list.",
    "luthier_fill_in_key_and_value_to_add_a_new_row": "Fill in key and value to add a new row.",
    "luthier_choose_file": "Choose file",
    "luthier_select_a_file_to_fill_this_field_automatically": "Select a file to fill this field automatically.",
    "luthier_label_cancel": "Cancel",
    "luthier_label_confirm": "Confirm",
    "luthier_label_remove": "Remove",
    "luthier_no_item_added": "No item added.",
    "luthier_key": "Key",
    "luthier_value": "Value",
    "luthier_open_menu": "Open menu",
    "luthier_step": "Step",
    "luthier_game_name": "Game name",
    "luthier_name_shown_in_splash_and_local_database": "Name shown in splash and local database.",
    "luthier_splash_hero_image": "Splash hero image",
    "luthier_hero_image_used_as_splash_background_downloaded_and_emb": "Background image used by the splash. Downloaded, center-cropped (96:31), converted to WebP and embedded into the generated executable.",
    "luthier_hero_image_ratio_96_31_and_converted_to_webp": "Target aspect ratio is 96:31. Non-matching images are center-cropped and resized.",
    "luthier_no_hero_image_selected": "No hero image selected.",
    "luthier_splash_hero_image_preview": "Splash hero image preview",
    "luthier_search_automatically": "Search automatically",
    "luthier_search_another": "Find another",
    "luthier_searching": "Searching...",
    "luthier_processing": "Processing...",
    "luthier_processing_hero_image": "Processing hero image...",
    "luthier_type_game_name_before_searching_hero_image": "Type the game name before searching the hero image automatically.",
    "luthier_searching_hero_image": "Searching hero image automatically...",
    "luthier_hero_image_found_processing_preview": "Hero image found. Processing preview...",
    "luthier_hero_image_ready_size": "Hero image ready ({width}x{height}).",
    "luthier_failed_to_search_hero_image_error": "Failed to search hero image: {error}",
    "luthier_failed_to_prepare_hero_image_error": "Failed to process hero image: {error}",
    "luthier_main_executable_exe": "Main executable (.exe)",
    "luthier_use_picker_to_select_the_real_game_executable": "Use picker to select the real game executable.",
    "luthier_select_file": "Select file",
    "luthier_game_root_folder": "Game root folder",
    "luthier_defaults_to_the_main_executable_folder_but_can_be_change": "Defaults to the main executable folder, but can be changed if the .exe is in a subfolder.",
    "luthier_choose_another": "Choose another",
    "luthier_choose_game_root_folder": "Choose game root folder",
    "luthier_the_game_root_must_be_an_ancestor_of_the_folder_that_con": "The game root must be an ancestor of the folder that contains the main executable.",
    "luthier_this_guided_flow_requires_an_absolute_executable_path_lo": "This guided flow requires an absolute executable path (local Tauri mode).",
    "luthier_use_system_picker": "Use system picker",
    "luthier_executable_folder_breadcrumb": "Executable folder breadcrumb",
    "luthier_executable_path": "Executable path",
    "luthier_select_which_ancestor_level_should_be_the_game_root": "Select which ancestor level should be the game root.",
    "luthier_same_directory_as_executable_automatic": "Same directory as executable (automatic)",
    "luthier_close": "Close",
    "luthier_sha_256_hash": "SHA-256 hash",
    "luthier_main_identifier_for_profile_and_per_game_prefix": "Main identifier for profile and per-game prefix.",
    "luthier_final_prefix_path": "Final prefix path",
    "luthier_automatically_calculated_from_executable_hash": "Automatically calculated from executable hash.",
    "luthier_prefix_path_copied": "Prefix path copied.",
    "luthier_failed_to_copy_to_clipboard": "Failed to copy to clipboard.",
    "luthier_copy": "Copy",
    "luthier_extracted_icon": "Extracted icon",
    "luthier_game_icon_preview_for_easier_visual_identification": "Game icon preview for easier visual identification.",
    "luthier_visual_is_ready_real_extraction_will_be_wired_to_backend": "Extracts the .exe icon for preview and saves a PNG next to the generated binary.",
    "luthier_no_extracted_icon": "No extracted icon",
    "luthier_extract_icon": "Extract icon",
    "luthier_launch_arguments": "Launch arguments",
    "luthier_extra_arguments_passed_to_game_executable": "Extra arguments passed to game executable.",
    "luthier_windowed": "-windowed",
    "luthier_add_argument": "Add argument",
    "luthier_no_launch_argument_added": "No launch argument added.",
    "luthier_argument": "Argument",
    "luthier_required_files": "Required files",
    "luthier_if_any_listed_file_is_missing_from_the_game_folder_start": "If any listed file is missing from the game folder, startup is blocked.",
    "luthier_data_core_dll": "./data/core.dll",
    "luthier_add_file": "Add file",
    "luthier_pick_file_from_game_folder": "Pick file from game folder",
    "luthier_no_file_added": "No file added.",
    "luthier_relative_file": "Relative file",
    "luthier_mounted_folders": "Mounted folders",
    "luthier_maps_a_folder_inside_the_game_to_a_windows_target_inside": "Maps a folder inside the game to a Windows target inside the prefix (e.g. saves under Documents).",
    "luthier_no_mount_added": "No mount added.",
    "luthier_relative_source": "Relative source",
    "luthier_windows_target": "Windows target",
    "luthier_create_source": "Create source",
    "luthier_yes": "Yes",
    "luthier_no": "No",
    "luthier_folder": "Folder",
    "luthier_remove_mount": "Remove mount",
    "luthier_add_mount": "Add mount",
    "luthier_set_relative_source_and_windows_target_to_create_the_mou": "Set relative source and Windows target to create the mount.",
    "luthier_relative_source_e_g_save": "Relative source (e.g. save)",
    "luthier_browse_folders": "Browse folders",
    "luthier_folders": "Folders",
    "luthier_files": "Files",
    "luthier_windows_target_c_users": "Windows target (C:\\users\\...)",
    "luthier_create_source_if_missing": "Create source if missing",
    "luthier_select_folder_inside_game": "Select folder inside game",
    "luthier_mini_browser_restricted_to_the_game_root_to_prevent_moun": "Mini browser restricted to the game root to prevent mounts outside the project.",
    "luthier_current_path": "Current path",
    "luthier_folder_breadcrumb": "Folder breadcrumb",
    "luthier_loading_folders": "Loading folders...",
    "luthier_loading_files": "Loading files...",
    "luthier_no_subfolder_found": "No subfolder found.",
    "luthier_no_file_found_in_current_folder": "No file found in this folder.",
    "luthier_select_this_folder": "Select this folder",
    "luthier_use_this_folder": "Use this folder",
    "luthier_select_file_inside_game": "Select file inside game",
    "luthier_mini_file_browser_restricted_to_the_game_root_to_prevent": "Mini file browser restricted to the game root to prevent selecting files outside the project.",
    "luthier_general_runtime_preference": "General runtime preference",
    "luthier_macro_priority_among_auto_proton_and_wine": "Macro priority among Auto, Proton and Wine.",
    "luthier_required_version": "Required version",
    "luthier_when_enabled_requires_the_configured_runtime_version_to": "When enabled, requires the configured runtime version to launch.",
    "luthier_auto_update": "Auto update",
    "luthier_updates_runtime_metadata_when_applicable_before_launchin": "Updates runtime metadata when applicable before launching.",
    "luthier_enables_synchronization_optimizations_in_runtime": "Enables synchronization optimizations in runtime.",
    "luthier_enables_fsync_optimizations_when_supported": "Enables FSYNC optimizations when supported.",
    "luthier_controls_umu_run_usage_according_to_enforcement_policy": "Controls umu-run usage according to enforcement policy.",
    "luthier_steam_runtime": "Steam Runtime",
    "luthier_defines_whether_steam_runtime_is_mandatory_optional_or_b": "Defines whether steam runtime is mandatory, optional or blocked.",
    "luthier_policy_for_local_easy_anticheat_runtime": "Policy for local Easy AntiCheat runtime.",
    "luthier_policy_for_local_battleeye_runtime": "Policy for local BattleEye runtime.",
    "luthier_defines_gamescope_policy_and_syncs_with_requirements_gam": "Defines gamescope policy and syncs with requirements.gamescope.",
    "luthier_gamescope_is_disabled_enable_it_to_configure_resolution": "Gamescope is disabled. Enable it to configure resolution, upscale and window mode.",
    "luthier_upscale_method": "Upscale method",
    "luthier_method_used_by_gamescope_for_upscaling": "Method used by gamescope for upscaling.",
    "luthier_window_type": "Window type",
    "luthier_defines_gamescope_window_behavior": "Defines gamescope window behavior.",
    "luthier_game_resolution": "Game resolution",
    "luthier_game_render_resolution_width_x_height": "Game render resolution (width x height).",
    "luthier_display_resolution": "Display resolution",
    "luthier_final_gamescope_output_resolution_width_x_height": "Final gamescope output resolution (width x height).",
    "luthier_auto": "Auto",
    "luthier_use_monitor_resolution": "Use monitor resolution",
    "luthier_enable_fps_limiter": "Enable FPS limiter",
    "luthier_enables_gamescope_fps_limiter": "Enables gamescope FPS limiter.",
    "luthier_force_grab_cursor": "Force grab cursor",
    "luthier_forces_relative_mouse_mode_to_avoid_focus_loss": "Forces relative mouse mode to avoid focus loss.",
    "luthier_fps_limit": "FPS limit",
    "luthier_fps_limit_when_game_is_focused": "FPS limit when game is focused.",
    "luthier_fps_limit_without_focus": "FPS limit without focus",
    "luthier_fps_limit_when_game_loses_focus": "FPS limit when game loses focus.",
    "luthier_fill_gamescope_game_resolution_before_creating": "Fill in the gamescope game resolution (width and height) before creating the executable.",
    "luthier_fill_gamescope_output_resolution_or_enable_monitor_auto_befo": "Fill in the gamescope display resolution (width and height) or enable \"Use monitor resolution\" before creating the executable.",
    "luthier_fill_gamescope_fps_limits_before_creating": "Fill in both FPS limiter values before creating the executable.",
    "luthier_gamescope_additional_options": "Gamescope additional options",
    "luthier_add_extra_flags_that_will_be_appended_to_the_gamescope_c": "Add extra flags that will be appended to the gamescope command.",
    "luthier_prefer_vk_device_1002_73bf": "--prefer-vk-device 1002:73bf",
    "luthier_add_option": "Add option",
    "luthier_defines_gamemode_policy": "Defines gamemode policy.",
    "luthier_defines_mangohud_policy": "Defines MangoHud policy.",
    "luthier_policy_for_enabling_wine_wayland": "Policy for enabling Wine-Wayland.",
    "luthier_policy_for_hdr_depends_on_wine_wayland": "Policy for HDR (depends on Wine-Wayland).",
    "luthier_controls_automatic_dxvk_nvapi_setup": "Controls automatic DXVK-NVAPI setup.",
    "luthier_controls_mandatory_usage_of_wine_staging_runtime": "Controls mandatory usage of Wine staging runtime.",
    "luthier_use_dedicated_gpu": "Use dedicated GPU",
    "luthier_exports_prime_render_offload_variables_to_try_using_the": "Exports PRIME render offload variables to try using the dedicated GPU on hybrid systems.",
    "luthier_enabled_automatically_when_at_least_one_verb_is_configur": "Enabled automatically when at least one verb is configured. Use search to add verbs from the catalog.",
    "luthier_remove_verb": "Remove verb",
    "luthier_failed_to_load_winetricks_catalog": "Failed to load winetricks catalog",
    "luthier_search_and_add_verbs_e_g_vcrun_corefonts": "Search and add verbs (e.g. vcrun, corefonts)",
    "luthier_the_local_remote_catalog_could_not_be_loaded_you_can_sti": "The local/remote catalog could not be loaded. You can still refresh the catalog manually.",
    "luthier_type_at_least_2_characters_to_search_verbs_in_the_catalo": "Type at least 2 characters to search verbs in the catalog.",
    "luthier_no_items_found": "No items found.",
    "luthier_loading_catalog_in_background": "Loading catalog in background...",
    "luthier_loading": "Loading...",
    "luthier_refresh_catalog": "Refresh catalog",
    "luthier_source": "Source:",
    "luthier_catalog": "Catalog:",
    "luthier_registry_keys": "Registry keys",
    "luthier_table_of_keys_applied_to_prefix_after_bootstrap": "Table of keys applied to prefix after bootstrap.",
    "luthier_no_key_added": "No key added.",
    "luthier_path": "Path",
    "luthier_name": "Name",
    "luthier_type": "Type",
    "luthier_remove_key": "Remove key",
    "luthier_add_key": "Add key",
    "luthier_add_registry_key": "Add registry key",
    "luthier_fill_fields_and_confirm_to_add_row": "Fill fields and confirm to add row.",
    "luthier_path_hkcu": "Path (HKCU\\...)",
    "luthier_key_name": "Key name",
    "luthier_type_reg_sz": "Type (REG_SZ)",
    "luthier_add_from_file_reg": "Add from file (.reg)",
    "luthier_reg_import_warnings": ".reg import warnings",
    "luthier_some_lines_were_ignored_or_imported_with_fallback_review": "Some lines were ignored or imported with fallback. Review the warnings below.",
    "luthier_extra_system_dependencies": "Extra system dependencies",
    "luthier_additional_dependencies_validated_in_doctor_by_command_e": "Additional dependencies validated in doctor by command/env/path.",
    "luthier_command": "Command",
    "luthier_env_vars": "Env vars",
    "luthier_default_paths": "Default paths",
    "luthier_unnamed": "Unnamed",
    "luthier_remove_dependency": "Remove dependency",
    "luthier_no_extra_dependency_added": "No extra dependency added.",
    "luthier_add_dependency": "Add dependency",
    "luthier_add_extra_system_dependency": "Add extra system dependency",
    "luthier_define_how_doctor_can_detect_this_dependency_command_env": "Define how doctor can detect this dependency (command, env vars and default paths).",
    "luthier_dependency_name": "Dependency name",
    "luthier_terminal_command_e_g_mangohud": "Terminal command (e.g. mangohud)",
    "luthier_environment_vars_comma_separated": "Environment vars (comma-separated)",
    "luthier_default_paths_comma_separated": "Default paths (comma-separated)",
    "luthier_winecfg_overrides_do_not_replace_everything": "Winecfg overrides (do not replace everything)",
    "luthier_settings_in_this_tab_are_additive_overrides_on_top_of_wi": "Settings in this tab are additive overrides on top of Wine/prefix defaults. If you keep \"Default\", the orchestrator does not force that item.",
    "luthier_dll_overrides": "DLL overrides",
    "luthier_configures_per_dll_overrides_such_as_native_builtin": "Configures per-DLL overrides such as native/builtin.",
    "luthier_no_override_added": "No override added.",
    "luthier_dll": "DLL",
    "luthier_mode": "Mode",
    "luthier_add_dll_override": "Add DLL override",
    "luthier_set_the_dll_name_and_override_mode": "Set the DLL name and override mode.",
    "luthier_windows_version_winecfg": "Windows version (winecfg)",
    "luthier_optional_override_for_the_windows_version_reported_by_th": "Optional override for the Windows version reported by the prefix. If unset, runtime/prefix defaults are kept.",
    "luthier_graphics": "Graphics",
    "luthier_equivalent_to_the_graphics_tab_in_winecfg_everything_her": "Equivalent to the Graphics tab in winecfg. Everything here is an additive override to prefix defaults.",
    "luthier_graphics_incremental_overrides": "Graphics = incremental overrides",
    "luthier_these_items_do_not_recreate_the_prefix_they_only_add_win": "These items do not recreate the prefix. They only add winecfg behavior overrides on top of what already exists in the current prefix.",
    "luthier_automatically_capture_mouse_in_fullscreen_windows": "Automatically capture mouse in fullscreen windows",
    "luthier_equivalent_to_winecfg_auto_capture_mouse_option": "Equivalent to winecfg auto-capture mouse option.",
    "luthier_allow_the_window_manager_to_decorate_windows": "Allow the window manager to decorate windows",
    "luthier_controls_window_decorations_managed_by_the_wm": "Controls window decorations managed by the WM.",
    "luthier_allow_the_window_manager_to_control_windows": "Allow the window manager to control windows",
    "luthier_lets_the_wm_control_window_position_focus_state": "Lets the WM control window position/focus/state.",
    "luthier_emulate_a_virtual_desktop": "Emulate a virtual desktop",
    "luthier_when_enabled_the_game_runs_inside_a_wine_virtual_desktop": "When enabled, the game runs inside a Wine virtual desktop.",
    "luthier_virtual_desktop_size": "Virtual desktop size",
    "luthier_set_width_x_height_e_g_1280_x_720": "Set width x height (e.g. 1280 x 720).",
    "luthier_screen_resolution_dpi": "Screen resolution (DPI)",
    "luthier_slider_from_96_dpi_to_480_dpi_if_unset_wine_default_is_u": "Slider from 96 DPI to 480 DPI. If unset, Wine default is used.",
    "luthier_use_default": "Use default",
    "luthier_default": "default",
    "luthier_desktop_integration": "Desktop integration",
    "luthier_file_protocol_associations_and_wine_special_desktop_fold": "File/protocol associations and Wine special desktop folder mappings.",
    "luthier_integration_can_affect_user_system_behavior": "Integration can affect user system behavior",
    "luthier_mime_protocol_associations_and_special_folders_can_chang": "MIME/protocol associations and special folders can change desktop integration behavior. Configure only what the game needs.",
    "luthier_desktop_integration_general": "Desktop integration (general)",
    "luthier_controls_wine_integration_with_the_linux_shell_desktop": "Controls Wine integration with the Linux shell/desktop.",
    "luthier_mime_types_file_protocol_associations": "MIME types (file/protocol associations)",
    "luthier_equivalent_to_manage_file_and_protocol_associations": "Equivalent to \"Manage file and protocol associations\".",
    "luthier_special_folders": "Special folders",
    "luthier_add_folder_shortcut_mappings_for_wine_optional_override": "Add folder + shortcut mappings for Wine (optional override).",
    "luthier_add_folder": "Add folder",
    "luthier_add_wine_special_folder": "Add Wine special folder",
    "luthier_set_folder_type_shortcut_name_and_linux_path": "Set folder type, shortcut name and Linux path.",
    "luthier_shortcut_name_in_wine": "Shortcut name in Wine",
    "luthier_prefer_generic_paths_without_a_fixed_username_when_possi": "Prefer generic paths (without a fixed username) when possible.",
    "luthier_no_special_folder_added": "No special folder added.",
    "luthier_shortcut": "Shortcut",
    "luthier_linux_path": "Linux path",
    "luthier_drives": "Drives",
    "luthier_additional_wine_drives_as_overrides_c_and_z_usually_alre": "Additional Wine drives as overrides. C: and Z: usually already exist in the default prefix.",
    "luthier_wine_drives_require_care": "Wine drives require care",
    "luthier_c_and_z_usually_already_exist_in_the_default_prefix_add": "C: and Z: usually already exist in the default prefix. Add new drives only when the game really depends on it and prefer generic Linux paths.",
    "luthier_usually_points_to_drive_c_internal_prefix_path": "usually points to drive_c (internal prefix path).",
    "luthier_usually_exposes_the_linux_filesystem_root_for_compatibil": "usually exposes the Linux filesystem root for compatibility.",
    "luthier_restore_shown_default_z": "Restore shown default (Z:)",
    "luthier_add_drive": "Add drive",
    "luthier_add_wine_drive": "Add Wine drive",
    "luthier_choose_an_available_letter_and_configure_drive_metadata": "Choose an available letter and configure drive metadata.",
    "luthier_label_optional": "Label (optional)",
    "luthier_serial_optional": "Serial (optional)",
    "luthier_use_a_generic_linux_directory_when_possible_avoid_user_s": "Use a generic Linux directory when possible (avoid user-specific absolute paths).",
    "luthier_that_drive_letter_is_already_in_use": "That drive letter is already in use.",
    "luthier_no_additional_drive_configured": "No additional drive configured.",
    "luthier_letter": "Letter",
    "luthier_label": "Label",
    "luthier_serial": "Serial",
    "luthier_audio": "Audio",
    "luthier_additional_audio_settings_from_winecfg_runtime_defaults": "Additional audio settings from winecfg. Runtime defaults remain valid if nothing is changed.",
    "luthier_audio_change_only_if_needed": "Audio: change only if needed",
    "luthier_forcing_an_audio_backend_can_fix_compatibility_but_may_w": "Forcing an audio backend can fix compatibility, but may worsen behavior on other hosts. Runtime default is usually the most portable option.",
    "luthier_audio_driver": "Audio driver",
    "luthier_select_the_preferred_backend_runtime_default_keeps_wine": "Select the preferred backend. \"Runtime default\" keeps Wine default behavior.",
    "luthier_wrapper_commands": "Wrapper commands",
    "luthier_commands_executed_before_the_main_runtime_e_g_gamescope": "Commands executed before the main runtime (e.g. gamescope, gamemoderun, mangohud).",
    "luthier_no_wrapper_command_added": "No wrapper command added.",
    "luthier_executable": "Executable",
    "luthier_arguments": "Arguments",
    "luthier_remove_wrapper": "Remove wrapper",
    "luthier_add_wrapper": "Add wrapper",
    "luthier_set_policy_executable_and_wrapper_arguments": "Set policy, executable and wrapper arguments.",
    "luthier_executable_e_g_gamescope": "Executable (e.g. gamescope)",
    "luthier_args_e_g_w_1920_h_1080": "Args (e.g. -w 1920 -h 1080)",
    "luthier_environment_variables": "Environment variables",
    "luthier_applied_at_launch_protected_keys_are_ignored_by_runtime": "Applied at launch (protected keys are ignored by runtime).",
    "luthier_add_variable": "Add variable",
    "luthier_no_environment_variable_added": "No environment variable added.",
    "luthier_variable": "Variable",
    "luthier_runtime_protected_keys": "Runtime-protected keys",
    "luthier_the_keys_below_are_reserved_if_added_above_they_will_be": "The keys below are reserved. If added above, they will be ignored by the orchestrator.",
    "luthier_pre_launch_script_bash": "Pre-launch script (bash)",
    "luthier_executed_before_starting_the_game": "Executed before starting the game.",
    "luthier_post_launch_script_bash": "Post-launch script (bash)",
    "luthier_executed_after_the_game_exits": "Executed after the game exits.",
    "luthier_local_scripts_mvp": "Local scripts (MVP)",
    "luthier_scripts_accept_bash_only_and_local_execution_in_the_mvp": "Scripts accept bash only and local execution in the MVP.",
    "luthier_scripts_are_not_sent_to_the_community_api_use_trusted_co": "Scripts are not sent to the community API. Use trusted commands only.",
    "luthier_configuration_summary": "Configuration summary",
    "luthier_quick_view_of_how_many_items_were_configured_in_each_sec": "Quick view of how many items were configured in each section.",
    "luthier_launch_arguments_2": "Launch arguments",
    "luthier_windows_registry": "Windows Registry",
    "luthier_mounts": "Mounts",
    "luthier_wrappers": "Wrappers",
    "luthier_configuration_preview_json": "Configuration preview (JSON)",
    "luthier_last_action_result": "Last action result",
    "luthier_back": "Back",
    "luthier_next": "Next",
    "luthier_mandatory_enabled": "Mandatory: Enabled",
    "luthier_mandatory_disabled": "Mandatory: Disabled",
    "luthier_optional_enabled": "Optional: Enabled",
    "luthier_optional_disabled": "Optional: Disabled",
    "luthier_runtime_default": "Runtime default",
    "luthier_integer_scaling": "Integer Scaling",
    "luthier_stretch_image": "Stretch image",
    "luthier_fullscreen": "Fullscreen",
    "luthier_borderless": "Borderless",
    "luthier_windowed_2": "Windowed",
    "luthier_select_an_executable_before_hashing": "Select an executable before hashing.",
    "luthier_hashing_requires_an_absolute_path_in_browser_lan_mode_us": "Hashing requires an absolute path. In browser/LAN mode, use the local Tauri app.",
    "luthier_select_game_executable": "Select game executable",
    "luthier_select_a_valid_windows_launcher_exe_bat_cmd_com": "Select a valid Windows launcher (.exe, .bat, .cmd, .com).",
    "luthier_select_reg_file": "Select .reg file",
    "luthier_select_game_root_folder": "Select game root folder",
    "luthier_the_selected_game_root_must_contain_the_main_executable": "The selected game root must contain the main executable.",
    "luthier_select_required_file": "Select required file",
    "luthier_selected_file_must_be_inside_the_game_root_folder": "Selected file must be inside the game root folder.",
    "luthier_select_folder_to_mount": "Select folder to mount",
    "luthier_selected_folder_must_be_inside_game_root_folder": "Selected folder must be inside game root folder.",
    "luthier_icon_extraction_will_be_wired_to_backend_in_the_next_fun": "Icon extraction will be wired to backend in the next functional step.",
    "luthier_select_an_executable_before_extracting_icon": "Select an executable before extracting the icon.",
    "luthier_icon_extraction_requires_an_absolute_path_in_browser_lan_m": "Icon extraction requires an absolute path. In browser/LAN mode, use the local Tauri app.",
    "luthier_extracting_icon_from_executable": "Extracting icon from executable...",
    "luthier_executable_icon_extracted_size": "Executable icon extracted ({width}x{height}).",
    "luthier_failed_to_extract_executable_icon_error": "Failed to extract executable icon: {error}",
    "luthier_type_at_least_2_characters_and_select_a_valid_catalog_ve": "Type at least 2 characters and select a valid catalog verb.",
    "luthier_winetricks_catalog_loaded_count": "Winetricks catalog loaded ({count} items).",
    "luthier_failed_to_load_winetricks_catalog_error": "Failed to load Winetricks catalog: {error}",
    "luthier_registry_import_warning_suffix_count": " ({count} warning(s) while importing)",
    "luthier_imported_registry_keys_from_reg_file": "Imported {count} registry key(s) from .reg file{warningSuffix}.",
    "luthier_failed_to_import_reg_file_error": "Failed to import .reg file: {error}",
    "luthier_failed_to_list_folders_error": "Failed to list folders: {error}",
    "luthier_game_root_hint_invalid_exe_outside_root": "Invalid: the main executable must be inside the game root.",
    "luthier_game_root_hint_manual_override": "Game root manually overridden.",
    "luthier_game_root_hint_auto": "Automatic game root based on the executable.",
    "luthier_executable_lives_in_relative_path": "Executable lives in: ./{path}",
} as const
