export const luthierMessagesPtBR = {
    "luthier_label_game": "Jogo",
    "luthier_label_game_files_and_launch": "Arquivos e Inicialização",
    "luthier_label_runtime": "Runtime",
    "luthier_enhancements": "Melhorias",
    "luthier_dependencies": "Dependências",
    "luthier_launch_and_environment": "Execução e Ambiente",
    "luthier_label_scripts": "Scripts",
    "luthier_review_and_generate": "Revisão e Gerar",
    "luthier_summary_game_root": "Pasta raiz",
    "luthier_summary_strict_proton_version": "Versão estrita do proton",
    "luthier_summary_windows_version": "Windows",
    "luthier_summary_virtual_desktop": "Desktop virtual",
    "luthier_summary_mime_protocols": "MIME/Protocolos",
    "luthier_runtime_default_do_not_override": "Padrão do runtime (não alterar)",
    "luthier_desktop": "Desktop",
    "luthier_documents": "Documentos",
    "luthier_downloads": "Downloads",
    "luthier_music": "Músicas",
    "luthier_pictures": "Imagens",
    "luthier_videos": "Vídeos",
    "luthier_auto_detect": "Auto detectar",
    "luthier_local_hard_disk": "Disco rígido local",
    "luthier_network_share": "Compartilhamento de rede",
    "luthier_floppy_disk": "Disquete",
    "luthier_cd_rom": "CD-ROM",
    "luthier_proton_version": "Versão do Proton",
    "luthier_wine_version": "Versão do Wine",
    "luthier_preferred_runtime_version": "Versão de runtime (preferida)",
    "luthier_target_proton_version_used_by_the_orchestrator_when_pref": "Versão alvo do Proton usada pelo Luthier Orchestrator quando a preferência está em Proton.",
    "luthier_expected_wine_version_identifier_when_preference_is_wine": "Versão/identificador de Wine esperada quando a preferência está em Wine.",
    "luthier_preferred_runtime_version_when_auto_mode_picks_proton_wi": "Versão preferida para runtime quando o modo Auto escolher Proton/Wine conforme disponibilidade.",
    "luthier_importing_reg_requires_an_absolute_path_in_browser_lan_m": "Importação de .reg requer caminho absoluto. No modo navegador (LAN), selecione no app Tauri local.",
    "luthier_mounted_folder_browser_requires_an_absolute_game_root_pa": "Navegador de pastas montadas requer caminho absoluto da pasta do jogo. Use o app Tauri local.",
    "luthier_required_file_browser_requires_an_absolute_game_root_pat": "Navegador de arquivos obrigatórios requer caminho absoluto da pasta do jogo. Use o app Tauri local.",
    "luthier_select_an_executable_first_to_define_the_game_folder": "Selecione um executável primeiro para definir a pasta do jogo.",
    "luthier_in_browser_lan_mode_the_mini_folder_browser_cannot_acces": "No modo navegador (LAN), o mini navegador de pastas não consegue acessar o filesystem. Use o app Tauri local.",
    "luthier_in_browser_lan_mode_the_mini_file_browser_cannot_access_": "No modo navegador (LAN), o mini navegador de arquivos não consegue acessar o filesystem. Use o app Tauri local.",
    "luthier_failed_to_list_files_error": "Falha ao listar arquivos: {error}",
    "luthier_language": "Idioma",
    "luthier_dark": "Escuro",
    "luthier_light": "Claro",
    "luthier_system": "Sistema",
    "luthier_theme": "Tema",
    "luthier_label_enabled": "Ativado",
    "luthier_label_disabled": "Desativado",
    "luthier_label_mandatory": "Obrigatório",
    "luthier_undo": "Desfazer",
    "luthier_registry_import_undone": "Importação de registro desfeita.",
    "luthier_use_wine_default": "Padrão",
    "luthier_label_actions": "Ações",
    "luthier_label_action": "Ação",
    "luthier_label_add": "Adicionar",
    "luthier_add_item": "Adicionar item",
    "luthier_enter_a_value_and_confirm_to_add_it_to_the_list": "Informe um valor e confirme para adicioná-lo à lista.",
    "luthier_fill_in_key_and_value_to_add_a_new_row": "Preencha chave e valor para adicionar uma nova linha.",
    "luthier_choose_file": "Escolher arquivo",
    "luthier_select_a_file_to_fill_this_field_automatically": "Selecione um arquivo para preencher este campo automaticamente.",
    "luthier_label_cancel": "Cancelar",
    "luthier_label_confirm": "Confirmar",
    "luthier_label_remove": "Remover",
    "luthier_no_item_added": "Nenhum item adicionado.",
    "luthier_key": "Chave",
    "luthier_value": "Valor",
    "luthier_open_menu": "Abrir menu",
    "luthier_step": "Etapa",
    "luthier_game_name": "Nome do jogo",
    "luthier_name_shown_in_splash_and_local_database": "Nome mostrado na splash e no banco local.",
    "luthier_splash_hero_image": "Hero image da splash",
    "luthier_hero_image_used_as_splash_background_downloaded_and_emb": "Imagem de fundo da splash. Baixada, cortada (96:31), convertida para WebP e embutida no executável gerado.",
    "luthier_hero_image_ratio_96_31_and_converted_to_webp": "Proporção alvo 96:31. Se a imagem vier diferente, ela é cortada no centro e redimensionada.",
    "luthier_no_hero_image_selected": "Nenhuma hero image selecionada.",
    "luthier_splash_hero_image_preview": "Preview da hero image da splash",
    "luthier_search_automatically": "Buscar automaticamente",
    "luthier_search_another": "Buscar outra",
    "luthier_searching": "Buscando...",
    "luthier_processing": "Processando...",
    "luthier_processing_hero_image": "Processando hero image...",
    "luthier_type_game_name_before_searching_hero_image": "Digite o nome do jogo antes de buscar a hero image automaticamente.",
    "luthier_searching_hero_image": "Buscando hero image automaticamente...",
    "luthier_hero_image_found_processing_preview": "Hero image encontrada. Processando preview...",
    "luthier_hero_image_ready_size": "Hero image pronta ({width}x{height}).",
    "luthier_failed_to_search_hero_image_error": "Falha ao buscar hero image: {error}",
    "luthier_failed_to_prepare_hero_image_error": "Falha ao processar hero image: {error}",
    "luthier_main_executable_exe": "Executável principal (.exe)",
    "luthier_use_picker_to_select_the_real_game_executable": "Use o picker para selecionar o .exe real do jogo.",
    "luthier_select_file": "Selecionar arquivo",
    "luthier_game_root_folder": "Pasta raiz do jogo",
    "luthier_defaults_to_the_main_executable_folder_but_can_be_change": "Por padrão usa a pasta do executável principal, mas pode ser alterada se o .exe estiver em subpasta.",
    "luthier_choose_another": "Escolher outra",
    "luthier_choose_game_root_folder": "Escolher pasta raiz do jogo",
    "luthier_the_game_root_must_be_an_ancestor_of_the_folder_that_con": "A pasta raiz deve ser um ancestral da pasta onde está o executável principal.",
    "luthier_this_guided_flow_requires_an_absolute_executable_path_lo": "Esse fluxo guiado precisa de um caminho absoluto do executável (modo Tauri local).",
    "luthier_use_system_picker": "Usar seletor do sistema",
    "luthier_executable_folder_breadcrumb": "Breadcrumb da pasta do executável",
    "luthier_executable_path": "Caminho do executável",
    "luthier_select_which_ancestor_level_should_be_the_game_root": "Selecione qual nível acima deve ser a pasta raiz do jogo.",
    "luthier_same_directory_as_executable_automatic": "Mesmo diretório do executável (automático)",
    "luthier_close": "Fechar",
    "luthier_sha_256_hash": "Hash SHA-256",
    "luthier_main_identifier_for_profile_and_per_game_prefix": "Identificador principal para perfil e prefixo por jogo.",
    "luthier_final_prefix_path": "Prefix path final",
    "luthier_automatically_calculated_from_executable_hash": "Calculado automaticamente a partir do hash do executável.",
    "luthier_prefix_path_copied": "Path do prefixo copiado.",
    "luthier_failed_to_copy_to_clipboard": "Falha ao copiar para área de transferência.",
    "luthier_copy": "Copiar",
    "luthier_extracted_icon": "Ícone extraído",
    "luthier_game_icon_preview_for_easier_visual_identification": "Preview do ícone do jogo para facilitar identificação visual.",
    "luthier_visual_is_ready_real_extraction_will_be_wired_to_backend": "Extrai o ícone do .exe para preview e salva um PNG ao lado do binário gerado.",
    "luthier_no_extracted_icon": "Sem ícone extraído",
    "luthier_extract_icon": "Extrair ícone",
    "luthier_launch_arguments": "Argumentos de launch",
    "luthier_extra_arguments_passed_to_game_executable": "Argumentos extras passados para o exe do jogo.",
    "luthier_windowed": "-windowed",
    "luthier_add_argument": "Adicionar argumento",
    "luthier_no_launch_argument_added": "Nenhum argumento adicionado.",
    "luthier_argument": "Argumento",
    "luthier_required_files": "Arquivos obrigatórios",
    "luthier_if_any_listed_file_is_missing_from_the_game_folder_start": "Se algum arquivo listado não existir na pasta do jogo, a inicialização é bloqueada.",
    "luthier_data_core_dll": "./data/core.dll",
    "luthier_add_file": "Adicionar arquivo",
    "luthier_pick_file_from_game_folder": "Escolher arquivo na pasta do jogo",
    "luthier_no_file_added": "Nenhum arquivo adicionado.",
    "luthier_relative_file": "Arquivo relativo",
    "luthier_mounted_folders": "Pastas montadas",
    "luthier_maps_a_folder_inside_the_game_to_a_windows_target_inside": "Mapeia uma pasta dentro do jogo para um destino Windows dentro do prefixo (ex.: saves em Documentos).",
    "luthier_no_mount_added": "Nenhuma montagem adicionada.",
    "luthier_relative_source": "Origem relativa",
    "luthier_windows_target": "Destino Windows",
    "luthier_create_source": "Criar origem",
    "luthier_yes": "Sim",
    "luthier_no": "Não",
    "luthier_folder": "Pasta",
    "luthier_remove_mount": "Remover montagem",
    "luthier_add_mount": "Adicionar montagem",
    "luthier_set_relative_source_and_windows_target_to_create_the_mou": "Defina origem relativa e destino Windows para criar a montagem.",
    "luthier_relative_source_e_g_save": "Origem relativa (ex.: save)",
    "luthier_browse_folders": "Navegar pastas",
    "luthier_folders": "Pastas",
    "luthier_files": "Arquivos",
    "luthier_windows_target_c_users": "Destino Windows (C:\\users\\...)",
    "luthier_create_source_if_missing": "Criar origem se estiver ausente",
    "luthier_select_folder_inside_game": "Selecionar pasta dentro do jogo",
    "luthier_mini_browser_restricted_to_the_game_root_to_prevent_moun": "Mini navegador restrito à pasta raiz do jogo para evitar montagens fora do projeto.",
    "luthier_current_path": "Caminho atual",
    "luthier_folder_breadcrumb": "Breadcrumb de pastas",
    "luthier_loading_folders": "Carregando pastas...",
    "luthier_loading_files": "Carregando arquivos...",
    "luthier_no_subfolder_found": "Nenhuma subpasta encontrada.",
    "luthier_no_file_found_in_current_folder": "Nenhum arquivo encontrado nesta pasta.",
    "luthier_select_this_folder": "Selecionar esta pasta",
    "luthier_use_this_folder": "Usar esta pasta",
    "luthier_select_file_inside_game": "Selecionar arquivo dentro da pasta do jogo",
    "luthier_mini_file_browser_restricted_to_the_game_root_to_prevent": "Mini navegador de arquivos restrito à pasta raiz do jogo para evitar selecionar arquivos fora do projeto.",
    "luthier_general_runtime_preference": "Preferência geral de runtime",
    "luthier_macro_priority_among_auto_proton_and_wine": "Prioridade macro entre Auto, Proton e Wine.",
    "luthier_required_version": "Versão obrigatória",
    "luthier_when_enabled_requires_the_configured_runtime_version_to": "Quando ativado, exige exatamente a versão configurada para executar.",
    "luthier_auto_update": "Auto update",
    "luthier_updates_runtime_metadata_when_applicable_before_launchin": "Atualiza metadados do runtime quando aplicável antes da execução.",
    "luthier_enables_synchronization_optimizations_in_runtime": "Ativa otimizações de sincronização no runtime.",
    "luthier_enables_fsync_optimizations_when_supported": "Ativa otimizações FSYNC quando suportado.",
    "luthier_controls_umu_run_usage_according_to_enforcement_policy": "Controla uso de umu-run conforme política de obrigatoriedade.",
    "luthier_steam_runtime": "Steam Runtime",
    "luthier_defines_whether_steam_runtime_is_mandatory_optional_or_b": "Define se steam runtime é obrigatório, opcional ou bloqueado.",
    "luthier_policy_for_local_easy_anticheat_runtime": "Política para runtime local do Easy AntiCheat.",
    "luthier_policy_for_local_battleeye_runtime": "Política para runtime local do BattleEye.",
    "luthier_defines_gamescope_policy_and_syncs_with_requirements_gam": "Define política do gamescope e sincroniza com requirements.gamescope.",
    "luthier_gamescope_is_disabled_enable_it_to_configure_resolution": "Gamescope está desativado. Ative para configurar resolução, upscale e janela.",
    "luthier_upscale_method": "Método de upscale",
    "luthier_method_used_by_gamescope_for_upscaling": "Método usado pelo gamescope para upscale.",
    "luthier_window_type": "Tipo de janela",
    "luthier_defines_gamescope_window_behavior": "Define comportamento da janela no gamescope.",
    "luthier_game_resolution": "Resolução do jogo",
    "luthier_game_render_resolution_width_x_height": "Resolução renderizada pelo jogo (largura x altura).",
    "luthier_display_resolution": "Resolução da tela",
    "luthier_final_gamescope_output_resolution_width_x_height": "Resolução final de saída do gamescope (largura x altura).",
    "luthier_auto": "Auto",
    "luthier_use_monitor_resolution": "Obter resolução do monitor",
    "luthier_enable_fps_limiter": "Limitar FPS",
    "luthier_enables_gamescope_fps_limiter": "Ativa limitador de FPS do gamescope.",
    "luthier_force_grab_cursor": "Forçar captura de cursor",
    "luthier_forces_relative_mouse_mode_to_avoid_focus_loss": "Força modo relativo de mouse para evitar perda de foco.",
    "luthier_fps_limit": "FPS limite",
    "luthier_fps_limit_when_game_is_focused": "Limite de FPS quando o jogo está em foco.",
    "luthier_fps_limit_without_focus": "FPS sem foco",
    "luthier_fps_limit_when_game_loses_focus": "Limite de FPS quando o jogo perde foco.",
    "luthier_fill_gamescope_game_resolution_before_creating": "Preencha a resolução do jogo no gamescope (largura e altura) antes de gerar o executável.",
    "luthier_fill_gamescope_output_resolution_or_enable_monitor_auto_befo": "Preencha a resolução de saída do gamescope (largura e altura) ou ative \"Obter resolução do monitor\" antes de gerar o executável.",
    "luthier_fill_gamescope_fps_limits_before_creating": "Preencha os dois valores do limitador de FPS antes de gerar o executável.",
    "luthier_gamescope_additional_options": "Opções adicionais do gamescope",
    "luthier_add_extra_flags_that_will_be_appended_to_the_gamescope_c": "Adicione flags extras que serão anexadas ao comando do gamescope.",
    "luthier_prefer_vk_device_1002_73bf": "--prefer-vk-device 1002:73bf",
    "luthier_add_option": "Adicionar opção",
    "luthier_defines_gamemode_policy": "Define política do gamemode.",
    "luthier_defines_mangohud_policy": "Define política do MangoHud.",
    "luthier_policy_for_enabling_wine_wayland": "Política para ativar Wine-Wayland.",
    "luthier_policy_for_hdr_depends_on_wine_wayland": "Política para HDR (depende de Wine-Wayland).",
    "luthier_controls_automatic_dxvk_nvapi_setup": "Controla aplicação automática de DXVK-NVAPI.",
    "luthier_controls_mandatory_usage_of_wine_staging_runtime": "Controla obrigatoriedade de runtime Wine com staging.",
    "luthier_use_dedicated_gpu": "Usar GPU dedicada",
    "luthier_exports_prime_render_offload_variables_to_try_using_the": "Exporta variáveis de PRIME render offload para tentar usar a GPU dedicada em sistemas híbridos.",
    "luthier_enabled_automatically_when_at_least_one_verb_is_configur": "Ativa automaticamente quando existir ao menos um verbo configurado. Use a busca para adicionar verbos do catálogo.",
    "luthier_remove_verb": "Remover verbo",
    "luthier_failed_to_load_winetricks_catalog": "Erro ao carregar o catálogo winetricks",
    "luthier_search_and_add_verbs_e_g_vcrun_corefonts": "Buscar e adicionar verbos (ex.: vcrun, corefonts)",
    "luthier_the_local_remote_catalog_could_not_be_loaded_you_can_sti": "O catálogo local/remoto não pôde ser carregado. Você ainda pode atualizar o catálogo manualmente.",
    "luthier_type_at_least_2_characters_to_search_verbs_in_the_catalo": "Digite ao menos 2 caracteres para buscar verbos no catálogo.",
    "luthier_no_items_found": "Nenhum item encontrado.",
    "luthier_loading_catalog_in_background": "Carregando catálogo em segundo plano...",
    "luthier_loading": "Carregando...",
    "luthier_refresh_catalog": "Atualizar catálogo",
    "luthier_source": "Fonte:",
    "luthier_catalog": "Catálogo:",
    "luthier_registry_keys": "Chaves de registro",
    "luthier_table_of_keys_applied_to_prefix_after_bootstrap": "Tabela de chaves aplicadas no prefixo após bootstrap.",
    "luthier_no_key_added": "Nenhuma chave adicionada.",
    "luthier_path": "Path",
    "luthier_name": "Nome",
    "luthier_type": "Tipo",
    "luthier_remove_key": "Remover chave",
    "luthier_add_key": "Adicionar chave",
    "luthier_add_registry_key": "Adicionar chave de registro",
    "luthier_fill_fields_and_confirm_to_add_row": "Preencha os campos e confirme para adicionar a linha.",
    "luthier_path_hkcu": "Path (HKCU\\...)",
    "luthier_key_name": "Nome da chave",
    "luthier_type_reg_sz": "Tipo (REG_SZ)",
    "luthier_add_from_file_reg": "Adicionar de arquivo (.reg)",
    "luthier_reg_import_warnings": "Avisos da importação de .reg",
    "luthier_some_lines_were_ignored_or_imported_with_fallback_review": "Algumas linhas foram ignoradas ou importadas com fallback. Revise os avisos abaixo.",
    "luthier_extra_system_dependencies": "Dependências extras do sistema",
    "luthier_additional_dependencies_validated_in_doctor_by_command_e": "Dependências adicionais verificadas no doctor por comando/env/path.",
    "luthier_command": "Comando",
    "luthier_env_vars": "Variáveis",
    "luthier_default_paths": "Paths padrão",
    "luthier_unnamed": "Sem nome",
    "luthier_remove_dependency": "Remover dependência",
    "luthier_no_extra_dependency_added": "Nenhuma dependência extra adicionada.",
    "luthier_add_dependency": "Adicionar dependência",
    "luthier_add_extra_system_dependency": "Adicionar dependência extra do sistema",
    "luthier_define_how_doctor_can_detect_this_dependency_command_env": "Informe como o doctor pode detectar essa dependência (comando, variáveis e paths padrão).",
    "luthier_dependency_name": "Nome da dependência",
    "luthier_terminal_command_e_g_mangohud": "Comando no terminal (ex.: mangohud)",
    "luthier_environment_vars_comma_separated": "Variáveis de ambiente (separadas por vírgula)",
    "luthier_default_paths_comma_separated": "Paths padrão (separados por vírgula)",
    "luthier_winecfg_overrides_do_not_replace_everything": "Overrides do winecfg (não substituem tudo)",
    "luthier_settings_in_this_tab_are_additive_overrides_on_top_of_wi": "As configurações desta aba são adicionais ao padrão do prefixo/Wine. Se você deixar em \"Padrão\", o Luthier Orchestrator não força esse item.",
    "luthier_dll_overrides": "Substituições de DLL",
    "luthier_configures_per_dll_overrides_such_as_native_builtin": "Configura overrides por DLL como native/builtin.",
    "luthier_no_override_added": "Nenhum override adicionado.",
    "luthier_dll": "DLL",
    "luthier_mode": "Modo",
    "luthier_add_dll_override": "Adicionar DLL override",
    "luthier_set_the_dll_name_and_override_mode": "Defina o nome da DLL e o modo de substituição.",
    "luthier_windows_version_winecfg": "Versão do Windows (winecfg)",
    "luthier_optional_override_for_the_windows_version_reported_by_th": "Override opcional da versão do Windows reportada pelo prefixo. Se não configurar, mantém o padrão do runtime/prefixo.",
    "luthier_graphics": "Gráficos",
    "luthier_equivalent_to_the_graphics_tab_in_winecfg_everything_her": "Equivalente à aba Gráficos do winecfg. Tudo aqui é adicional ao padrão do prefixo.",
    "luthier_graphics_incremental_overrides": "Gráficos = ajustes incrementais",
    "luthier_these_items_do_not_recreate_the_prefix_they_only_add_win": "Esses itens não recriam o prefixo. Eles apenas adicionam overrides de comportamento do winecfg sobre o que já existe no prefixo atual.",
    "luthier_automatically_capture_mouse_in_fullscreen_windows": "Capturar o mouse automaticamente em janelas em tela cheia",
    "luthier_equivalent_to_winecfg_auto_capture_mouse_option": "Equivalente à opção de captura automática do winecfg.",
    "luthier_allow_the_window_manager_to_decorate_windows": "Permitir que o gerenciador de janelas decore as janelas",
    "luthier_controls_window_decorations_managed_by_the_wm": "Controla decorações de janela gerenciadas pelo WM.",
    "luthier_allow_the_window_manager_to_control_windows": "Permitir que o gerenciador de janelas controle as janelas",
    "luthier_lets_the_wm_control_window_position_focus_state": "Permite que o WM controle posição/foco/estado das janelas.",
    "luthier_emulate_a_virtual_desktop": "Emular uma área de trabalho virtual",
    "luthier_when_enabled_the_game_runs_inside_a_wine_virtual_desktop": "Quando ativo, o jogo roda dentro de um desktop virtual do Wine.",
    "luthier_virtual_desktop_size": "Tamanho da área de trabalho virtual",
    "luthier_set_width_x_height_e_g_1280_x_720": "Informe largura x altura (ex.: 1280 x 720).",
    "luthier_screen_resolution_dpi": "Resolução da tela (DPI)",
    "luthier_slider_from_96_dpi_to_480_dpi_if_unset_wine_default_is_u": "Slider de 96 ppp até 480 ppp. Se não configurar, usa o padrão do Wine.",
    "luthier_use_default": "Usar padrão",
    "luthier_default": "padrão",
    "luthier_desktop_integration": "Integração com área de trabalho",
    "luthier_file_protocol_associations_and_wine_special_desktop_fold": "Associações de arquivo/protocolo e mapeamentos de pastas especiais do Wine.",
    "luthier_integration_can_affect_user_system_behavior": "Integração pode afetar o sistema do usuário",
    "luthier_mime_protocol_associations_and_special_folders_can_chang": "Associações MIME/protocolo e pastas especiais podem alterar integração com desktop. Prefira configurar apenas o necessário para o jogo.",
    "luthier_desktop_integration_general": "Integração com desktop (geral)",
    "luthier_controls_wine_integration_with_the_linux_shell_desktop": "Controla integração do Wine com shell/desktop do Linux.",
    "luthier_mime_types_file_protocol_associations": "Tipos MIME (associações de arquivo e protocolo)",
    "luthier_equivalent_to_manage_file_and_protocol_associations": "Equivalente a \"Manage file and protocol associations\".",
    "luthier_special_folders": "Pastas especiais",
    "luthier_add_folder_shortcut_mappings_for_wine_optional_override": "Adicione mapeamentos de pasta e atalho para o Wine (override opcional).",
    "luthier_add_folder": "Adicionar pasta",
    "luthier_add_wine_special_folder": "Adicionar pasta especial do Wine",
    "luthier_set_folder_type_shortcut_name_and_linux_path": "Defina o tipo da pasta, nome do atalho e caminho Linux.",
    "luthier_shortcut_name_in_wine": "Nome do atalho no Wine",
    "luthier_prefer_generic_paths_without_a_fixed_username_when_possi": "Prefira caminhos genéricos (sem nome de usuário fixo), quando possível.",
    "luthier_no_special_folder_added": "Nenhuma pasta especial adicionada.",
    "luthier_shortcut": "Atalho",
    "luthier_linux_path": "Caminho Linux",
    "luthier_drives": "Unidades",
    "luthier_additional_wine_drives_as_overrides_c_and_z_usually_alre": "Unidades adicionais do Wine como overrides. C: e Z geralmente já existem no prefixo padrão.",
    "luthier_wine_drives_require_care": "Unidades do Wine exigem cuidado",
    "luthier_c_and_z_usually_already_exist_in_the_default_prefix_add": "C: e Z: normalmente já existem no prefixo padrão. Adicione novas unidades apenas quando o jogo realmente depender disso e prefira caminhos Linux genéricos.",
    "luthier_usually_points_to_drive_c_internal_prefix_path": "normalmente aponta para drive_c (interno do prefixo).",
    "luthier_usually_exposes_the_linux_filesystem_root_for_compatibil": "geralmente expõe a raiz do filesystem Linux por compatibilidade.",
    "luthier_restore_shown_default_z": "Restaurar padrão exibido (Z:)",
    "luthier_add_drive": "Adicionar unidade",
    "luthier_add_wine_drive": "Adicionar unidade do Wine",
    "luthier_choose_an_available_letter_and_configure_drive_metadata": "Escolha uma letra disponível e configure os metadados da unidade.",
    "luthier_label_optional": "Rótulo (opcional)",
    "luthier_serial_optional": "Serial (opcional)",
    "luthier_use_a_generic_linux_directory_when_possible_avoid_user_s": "Use um diretório Linux genérico quando possível (evite paths fixos com nome de usuário).",
    "luthier_that_drive_letter_is_already_in_use": "Essa letra de unidade já está em uso.",
    "luthier_no_additional_drive_configured": "Nenhuma unidade adicional configurada.",
    "luthier_letter": "Letra",
    "luthier_label": "Rótulo",
    "luthier_serial": "Serial",
    "luthier_audio": "Áudio",
    "luthier_additional_audio_settings_from_winecfg_runtime_defaults": "Configurações adicionais de áudio do winecfg. O padrão do runtime continua válido se nada for alterado.",
    "luthier_audio_change_only_if_needed": "Áudio: altere só se precisar",
    "luthier_forcing_an_audio_backend_can_fix_compatibility_but_may_w": "Forçar backend de áudio pode resolver compatibilidade, mas também pode piorar em outros hosts. O padrão do runtime costuma ser a opção mais portátil.",
    "luthier_audio_driver": "Driver de áudio",
    "luthier_select_the_preferred_backend_runtime_default_keeps_wine": "Selecione o backend preferido. \"Padrão do runtime\" mantém o comportamento padrão do Wine.",
    "luthier_wrapper_commands": "Comandos de wrapper",
    "luthier_commands_executed_before_the_main_runtime_e_g_gamescope": "Comandos executados antes do runtime principal (ex.: gamescope, gamemoderun, mangohud).",
    "luthier_no_wrapper_command_added": "Nenhum comando de wrapper adicionado.",
    "luthier_executable": "Executável",
    "luthier_arguments": "Argumentos",
    "luthier_remove_wrapper": "Remover wrapper",
    "luthier_add_wrapper": "Adicionar wrapper",
    "luthier_set_policy_executable_and_wrapper_arguments": "Defina política, executável e argumentos do wrapper.",
    "luthier_executable_e_g_gamescope": "Executável (ex.: gamescope)",
    "luthier_args_e_g_w_1920_h_1080": "Args (ex.: -w 1920 -h 1080)",
    "luthier_environment_variables": "Variáveis de ambiente",
    "luthier_applied_at_launch_protected_keys_are_ignored_by_runtime": "Aplicadas no launch (chaves protegidas são ignoradas pelo runtime).",
    "luthier_add_variable": "Adicionar variável",
    "luthier_no_environment_variable_added": "Nenhuma variável de ambiente adicionada.",
    "luthier_variable": "Variável",
    "luthier_runtime_protected_keys": "Chaves protegidas pelo runtime",
    "luthier_the_keys_below_are_reserved_if_added_above_they_will_be": "As chaves abaixo são reservadas. Se forem adicionadas na lista acima, serão ignoradas pelo Luthier Orchestrator.",
    "luthier_pre_launch_script_bash": "Script antes de iniciar o jogo (bash)",
    "luthier_executed_before_starting_the_game": "Executado antes de iniciar o jogo.",
    "luthier_post_launch_script_bash": "Script após fechar o jogo (bash)",
    "luthier_executed_after_the_game_exits": "Executado após o jogo ser encerrado.",
    "luthier_local_scripts_mvp": "Scripts locais (MVP)",
    "luthier_scripts_accept_bash_only_and_local_execution_in_the_mvp": "Scripts aceitam apenas bash e execução local no MVP.",
    "luthier_scripts_are_not_sent_to_the_community_api_use_trusted_co": "Scripts não são enviados para a API comunitária. Use apenas comandos confiáveis.",
    "luthier_configuration_summary": "Resumo da configuração",
    "luthier_quick_view_of_how_many_items_were_configured_in_each_sec": "Visão rápida da quantidade de itens configurados em cada seção.",
    "luthier_launch_arguments_2": "Argumentos de inicialização",
    "luthier_windows_registry": "Registro do Windows",
    "luthier_mounts": "Montagens",
    "luthier_wrappers": "Wrappers",
    "luthier_configuration_preview_json": "Pré-visualização da configuração (JSON)",
    "luthier_last_action_result": "Resultado da última ação",
    "luthier_back": "Retornar",
    "luthier_next": "Avançar",
    "luthier_mandatory_enabled": "Obrigatório: Ativado",
    "luthier_mandatory_disabled": "Obrigatório: Desativado",
    "luthier_optional_enabled": "Opcional: Ativado",
    "luthier_optional_disabled": "Opcional: Desativado",
    "luthier_runtime_default": "Padrão do runtime",
    "luthier_integer_scaling": "Escala Inteira",
    "luthier_stretch_image": "Esticar imagem",
    "luthier_fullscreen": "Tela cheia",
    "luthier_borderless": "Sem borda",
    "luthier_windowed_2": "Janela",
    "luthier_select_an_executable_before_hashing": "Selecione um executável antes de calcular hash.",
    "luthier_hashing_requires_an_absolute_path_in_browser_lan_mode_us": "Calcular hash requer caminho absoluto. No modo navegador (LAN), use o app Tauri local.",
    "luthier_select_game_executable": "Selecionar executável do jogo",
    "luthier_select_a_valid_windows_launcher_exe_bat_cmd_com": "Selecione um executável Windows válido (.exe, .bat, .cmd, .com).",
    "luthier_select_reg_file": "Selecionar arquivo .reg",
    "luthier_select_game_root_folder": "Selecionar pasta raiz do jogo",
    "luthier_the_selected_game_root_must_contain_the_main_executable": "A pasta raiz escolhida deve conter o executável principal.",
    "luthier_select_required_file": "Selecionar arquivo obrigatório",
    "luthier_selected_file_must_be_inside_the_game_root_folder": "O arquivo selecionado precisa estar dentro da pasta raiz do jogo.",
    "luthier_select_folder_to_mount": "Selecionar pasta para montar",
    "luthier_selected_folder_must_be_inside_game_root_folder": "A pasta selecionada precisa estar dentro da pasta raiz do jogo.",
    "luthier_icon_extraction_will_be_wired_to_backend_in_the_next_fun": "Extração de ícone será conectada ao backend na próxima etapa funcional.",
    "luthier_select_an_executable_before_extracting_icon": "Selecione um executável antes de extrair o ícone.",
    "luthier_icon_extraction_requires_an_absolute_path_in_browser_lan_m": "Extrair ícone requer caminho absoluto. No modo navegador (LAN), use o app Tauri local.",
    "luthier_extracting_icon_from_executable": "Extraindo ícone do executável...",
    "luthier_executable_icon_extracted_size": "Ícone extraído ({width}x{height}).",
    "luthier_failed_to_extract_executable_icon_error": "Falha ao extrair ícone do executável: {error}",
    "luthier_type_at_least_2_characters_and_select_a_valid_catalog_ve": "Digite ao menos 2 caracteres e selecione um verbo válido do catálogo.",
    "luthier_winetricks_catalog_loaded_count": "Catálogo Winetricks carregado ({count} itens).",
    "luthier_failed_to_load_winetricks_catalog_error": "Falha ao carregar catálogo Winetricks: {error}",
    "luthier_registry_import_warning_suffix_count": " ({count} aviso(s) ao importar)",
    "luthier_imported_registry_keys_from_reg_file": "Importadas {count} chave(s) de registro do arquivo .reg{warningSuffix}.",
    "luthier_failed_to_import_reg_file_error": "Falha ao importar arquivo .reg: {error}",
    "luthier_failed_to_list_folders_error": "Falha ao listar pastas: {error}",
    "luthier_game_root_hint_invalid_exe_outside_root": "Inválido: o executável principal precisa estar dentro da pasta raiz.",
    "luthier_game_root_hint_manual_override": "Pasta raiz alterada manualmente.",
    "luthier_game_root_hint_auto": "Pasta raiz automática baseada no executável.",
    "luthier_executable_lives_in_relative_path": "Executável fica em: ./{path}",
} as const
